### PR TITLE
new study: ccrcc_dfci_2019

### PR DESCRIPTION
**Pull request by yichaoS**
# What?
Fix https://github.com/cBioPortal/datahub/issues/739

For a new study (in addition to above):
- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [x] is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [x] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [x] clinical sample and patient data with meta files
- [x] mutations data with meta files
- [x] MAF is based on hg19
- [x] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [x] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

Triage Instance:
https://triage.cbioportal.mskcc.org/study/summary?id=ccrcc_dfci_2019#summary

### CODE REVIEW

**Comment by rmadupuri** [comment]
Few minor data issues:

- [ ] normal status in study description
- [ ] Does histology of the 35 discovery cohort samples also be `clear-cell`?
- [ ] can `overall survival censor` attribute be OS_STATUS and `Overall survival Days` be converted to OS_MONTHS (days to months) so the survival K-M plot can be displayed?
- [ ] can `progress free censor` attribute be PFS_STATUS and `progression free survival (days)` be PFS_MONTHS (days to months)
- [ ] oncotree code from `ccRCC` to `CCRCC` and cancer_type, cancer_type_detailed graphs are not shown on portal
- [ ] Do we have more detailed descriptions for the new clinical attributes (only if available)
- [ ] can purity and ploidy attributes from the WES sheet for both discovery and validation cohorts be added and genome_doubling attribute as well ( not sure what 0 and 1 infer here though)
- [ ] Do we know what 0 and 1 infer in words for OS_STATUS, PFS_STATUS and first line therapy? 
- [ ] I think few clinical attributes can be normalized to existing ones. For example,
	- ALL_NONSYNS -> NONSYNONYMOUS_MUTATION_COUNT
	- RESPONSE_CATEGORY -> IMMUNOTHERAPY_RESPONSE
	- BEST_RECIST -> RECIST
- [ ] Two PBRM1 `Nonsense_Mutations` are missing annotation (looks like ref_allele/position is wrong) showing up as `MUTATED` in portal.
- [ ] The PBRM1 FS Dels from two samples `KE5236, RCC_79-Tumor-SM-A46ER` seems to be not imported to portal. total 40 PBRM1 mutations from data file. portal shows 38. 
- [ ] Should the validation cohort be curated as well with this study? since only PBRM1 gene is sequenced in the validation cohort?

**Comment by yichaoS** [comment]
@ramya 
point 2: not sure (@ritika ?)
point 3 & 4 & 8: I agree os_censor and os_status could be somewhat the same, but I went through the literature again and it doesn't indicate anywhere what `0` and `1` are. Same for `pfs`
point 5: change ccRCC -> CCRCC; by default it is not showing CT, CTD because it's mono cancer type
point 6: not indicated in the literature, thus I just changed abbreviations into whole words
point 11: Both of those mutations are intron, therefore not imported

**Comment by yichaoS** [comment]
@ritikakundra @rmadupuri Fixed based on 2nd QC.

**Comment by yichaoS** [comment]
@ritikakundra @rmadupuri For the points of OS_censor / PFS_censor becoming OS_status / PFS_status, I'm still not sure if that's the case. Because in censor normally in the survival refers to the sample dropped out before the study ended, instead of the actual living/dead situation. I haven't find anywhere in the publication indication what specifically 0 and 1 means. So I suggest we keep the original header and values.

**Pull request merged**
