### PR TITLE
add study ucec_cptac_2020

### PR DESCRIPTION
**Pull request by egarcialara**
# What?
- added new study [Yongchao Dou et al. "Proteogenomic Characterization of Endometrial Carcinoma" Cell 2020](https://www.cell.com/cell/fulltext/S0092-8674(20)30107-0)
https://github.com/cBioPortal/datahub/issues/1065

:information_source:  See [README](https://github.com/cBioPortal/datahub/blob/ucec_cptac_2020/public/ucec_cptac_2020/README.md) for transformation process

Cancer studies updated in this pull request:
- ucec_cptac_2020

# checks
For all pull requests:
- [x] Passes validation

For a new study (in addition to above):
- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [x] is study meta data complete? e.g. pmid, group of PUBLIC
- [x] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [x] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [x] clinical sample and patient data with meta files
- [x] mutations data with meta files
- [x] MAF is based on hg19
- [ ] ~~MAF with 2 isoforms: uniprot and mskcc~~ _Not applicable_
- [x] CNA data with meta files
- [ ] ~~CNA segment data with meta files~~ _Not applicable_
- [x] Expression data including z-scores with meta files
- [x] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

Triage instance:
https://triage.cbioportal.mskcc.org/study/summary?id=ucec_cptac_2020

### CODE REVIEW

**Comment by yichaoS** [comment]
@egarcialara 

in clinical files:
- values of `cancer type` should be `Endometrial Carcinoma`
- add `oncotree_code` column to clinical sample and the values should be `UCEC`  
- `cancer type` and `cancer type detailed` should be in clinical sample instead of clinical patient
- underscore should be removed from the clinical header first line (attribute name) for proper display. 

methylation:
- methylation data should be in expression-like format (https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#methylation-data) instead of generic essay, thus this profile should be viewed in plots/co-exp etc. 

z-score
- I want to confirm `data_protein_quantification_zscores_ref_diploid_samples.txt` and `data_mrna_seq_rsem_zscores_ref_diploid_samples.txt` are against all diploid samples and not all samples? We don't have a script to generate against all diploid samples (the ones existed are directly from TCGA) and I don't see it is provided in publication. Or is this zscore data downloaded somewhere? 
- typo in `meta_mrna_seq_rsemm_zscores_ref_diploid_samples.txt` (rsemm -> rsem)

`meta_study.txt`
- remove `add_global_case_list
- short name missing space `CPTAC Cell2020`

case lists
- list fo log2CNA and list for all samples are missing.

**Review by SRodenburg — CHANGES_REQUESTED** [review]
Study does not validate:

```
ERROR: meta_methylation.txt: Could not determine the file type. Please check your meta files for correct configuration.; value encountered: 'genetic_alteration_type: METHYLATION, datatype: LIMIT-VALUE'

ERROR: meta_protein_quantification_zscores_ref_diploid_samples.txt: stable_id repeated. It should be unique across all files in a study; value encountered: 'protein_quantification_zscores'

ERROR: -: No case list found with stable_id 'ucec_cptac_2020_all', consider adding 'add_global_case_list: true' to the meta_study.txt file

ERROR: data_protein_quantification_zscores_ref_diploid_samples.txt: File could not be opened
```

The data file link in _meta_protein_quantification_zscores_ref_diploid_samples.txt_ is not correct.
I guess rename _data_protein_quantification_zscores.txt_ => _data_protein_quantification_zscores_ref_diploid_samples.txt_

**Comment by egarcialara** [comment]
Number of features in downloaded table:

- CNA: 28057
- RNA-seq: 28057
- protein: 10999
- mutations (maf): 53101 
- miRNA: 2337
- cRNA: 4945
- acetylprotein: 10862
- phosphoprotein: 73212

**Review by SRodenburg — APPROVED** [review]

**Comment by egarcialara** [comment]
Hi @yichaoS ,
Thank you as always for the comments
- I was removing duplicates for Entrez_Gene_Id, but I think it's better leaving them all as you suggest. Now the size of the tables is of 28057 rows for all (as in LinkedOmics). The affected tables tables are: `data_mrna_seq_rsem.txt`, `data_mrna_seq_rsem_zscores_ref_all_samples.txt`, `data_mrna_seq_rsem_zscores_ref_diploid_samples.txt`, `data_cna`, `daga_log2cna`. 
- For the matched samples, I added `MATCHED` for all samples. I was confused, as it seems that all samples are matched for the genomics data, but there are only "49 normal tissue samples for multi-omic characterization".

**Comment by yichaoS** [comment]
@egarcialara Merging this now. Created an issue for double confirm the matched normal status further: https://github.com/cBioPortal/datahub/issues/1567

**Pull request merged**
