### PR TITLE
Methylation as Generic Assay in Pan-can studies

### PR DESCRIPTION
**Pull request by yichaoS**
Testing instances

**Single study query**
- ov pancan (plots): https://bit.ly/3tU6EO0
Screen Shot 2022-01-24 at 11 01 25 AM

- hnsc pancan (oncoprint): https://bit.ly/3GVqQ5C
Screen Shot 2022-01-24 at 11 26 17 AM
Screen Shot 2022-01-24 at 11 06 01 AM

**Combined studies query**

> Issue 1
Since across cancer types for pancan we share the same probes, queries on combined studies (e.g. https://cbioportal.mskcc.org/study/summary?id=ov_tcga_pan_can_atlas_2018%2Chnsc_tcga_pan_can_atlas_2018) can't really distinguish between different studies, it seems as one probe was loaded twice(see first screenshot). But then only one of the two can be added (see screenshot 2). Should we add study ID in entity properties in this case? 
Screen Shot 2022-01-24 at 11 07 51 AM
Screen Shot 2022-01-24 at 11 23 34 AM

### CODE REVIEW

**Comment by jjgao** [comment]
Thanks, @yichaoS. Should we remove the duplicated "body;" strings...

image

**Comment by jjgao** [comment]
image

**Comment by jjgao** [comment]
@tmazor you may be able to test it though the private portal: https://bit.ly/3qTg9em

**Comment by yichaoS** [comment]
TODO (curation)
- [ ] remove duplicate "group" strings

TODO (front-end)
- [ ] In the OncoPrint tracks, can you show the full probe ID in the tooltip when hovering over the gene symbol?
- [ ] plots dropdown menu title change to "Gene / Probe"
- [ ] dropdown menu performance issue

**Comment by tmazor** [comment]
Thanks for the link @jjgao  - I can access the data there

I agree with all the comments above, and below are some additional suggestions.

1. In Charts/Add Tracks menus, the default text 'Search for Methylations' sounds funny. I realize for generic assay this text is just the plural of the data type (eg Arm-level CNAs), but it just doesn't work for Methylation. Can that be changed to something along the lines of 'Search for gene/probe'
image
2. Agree with the comment above about removing duplicates in the gene regions (eg just show Body once per probe).
image
3. What annotations are the basis of the gene regions? I was assuming it's the Illumina-provided annotations, but if I take cg07054526 (which shows up above as NA), and look it up in the file I downloaded from Illumina's website, it's annotated as Body/5'UTR.
4. I remember some conversations about the various color schemes for different types of OncoPrint heatmaps tracks, but at this point no longer remember all the details. The methylation tracks use dark blue (low methylation) to light blue (high methylation). Can we swap that? Darker colors seem more intuitive to me as higher methylation. If I add a microbiome track, those go from light orange to dark orange as scores increase.
image
5. General thought for the future: can we add a way to remove multiple tracks at once from OncoPrint? I added a bunch of DNA methylation tracks, and then wanted to get rid of them, but the only way to do that is to delete them one-by-one -- which is tedious and slow, especially because OncoPrint has to reload after each deletion.
6. Not sure if this is an existing bug or specific to this data, but after deleting the last track as described above, all the tracks returned. 
Jan-25-2022 17-41-38

**Comment by dippindots** [comment]
@tmazor I am working on address these issues now, just FYI the 5th comment in your feedback can be achieved by delete a whole group of tracks, here is an [example](https://www.cbioportal.org/results/oncoprint?cancer_study_list=hnsc_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Cgistic&case_set_id=hnsc_tcga_pan_can_atlas_2018_cnaseq&gene_list=TP53&geneset_list=%20&tab_index=tab_visualize&Action=Submit&generic_assay_groups=hnsc_tcga_pan_can_atlas_2018_microbiome_signature%2CPrasinovirus%2CSfi1unalikevirus): 
image

**Comment by tmazor** [comment]
Oh! Thanks for letting me know @dippindots - glad to realize we already have that

**Comment by yichaoS** [comment]
TODO (curation)
- [ ] remove duplicate "group" strings
- [ ] run "symbol clean up" script to make sure all symbols are up-to-date with our gene tables
- [ ] add `value_sort_order: DESC` to field to meta
- [ ] redo 450k probe info mapping

TODO items for front-end are logged here:
https://github.com/cBioPortal/cbioportal/issues/9253

**Pull request merged**
