### PR TITLE
Newly released studies

### PR DESCRIPTION
**Pull request by yichaoS**
all_phase2_target_2018_pub
aml_target_2018_pub
nbl_target_2018_pub
rt_target_2018_pub
wt_target_2018_pub
prad_p1000
prad_eururol_2017
nsclc_pd1_msk_2018
sclc_cancercell_gardner_2017
angs_project_painter_2018
all_stjude_2016
brca_mbcproject_wagle_2017

### CODE REVIEW

**Comment by pieterlukasse** [comment]
there is one file ending with .gz . Can you please unzip and store it plain text (lfs)?

**Comment by angelicaochoa** [comment]
@yichaoS I noticed that the seg data file for all_phase2_target_2018_pub  is not managed by git-lfs

**Comment by angelicaochoa** [comment]
@yichaoS I noticed that the seg data file for all_phase2_target_2018_pub  is not managed by git-lfs

**Comment by angelicaochoa** [comment]
@yichaoS 
data files that are not git-lfs managed:

- [ ]  all_phase2_target_2018_pub/all_phase2_target_2018_pub_data_cna_hg19.seg
- [ ]  aml_target_2018_pub/aml_target_2018_pub_data_cna_hg19.seg
- [ ] angs_project_painter_2018/data_cna_hg19.seg
- [ ] brca_mbcproject_wagle_2017/brca_mbcproject_wagle_2017_data_cna_hg19.seg
- [ ] nbl_target_2018_pub/nbl_target_2018_pub_data_cna_hg19.seg
- [ ] nsclc_pd1_msk_2018/nsclc_pd1_msk_2018_data_cna_hg19.seg
- [ ] prad_p1000/prad_p1000_data_cna_hg19.seg
- [ ] sclc_cancercell_gardner_2017/sclc_cancercell_gardner_2017_data_cna_hg19.seg

I also see some `meta_study.txt` files which are git-lfs managed - I thought all meta files were supposed to be managed with "regular" git?
- [ ] all_phase2_target_2018_pub/meta_study.txt
- [ ] all_stjude_2016/meta_study.txt
- [ ] aml_target_2018_pub/meta_study.txt
- [ ] angs_project_painter_2018/meta_study.txt
- [ ] brca_mbcproject_wagle_2017/meta_study.txt
- [ ] nbl_target_2018_pub/meta_study.txt
- [ ] nsclc_pd1_msk_2018/meta_study.txt
- [ ] prad_eururol_2017/meta_study.txt
- [ ] prad_p1000/meta_study.txt
- [ ] rt_target_2018_pub/meta_study.txt
- [ ] sclc_cancercell_gardner_2017/meta_study.txt

I see a bunch of other meta data files as git-lfs managed also (ex. meta_mutations_extended.txt). Maybe I'm just out of the loop but what is the format supposed to be @yichaoS @pieterlukasse @ritikakundra ?

**Comment by yichaoS** [comment]
@angelicaochoa The seg, data(.txt), .tar.gz, pdf are supported by LFS. The updated .gitattributes is in RC now (https://github.com/cBioPortal/datahub/blob/rc/.gitattributes) and I manually converted the LFS status for the studies that's already in. Guess I'll have to do the same here. Will follow up with a fix for the LFS status of the files you listed.

**Comment by yichaoS** [comment]
@angelicaochoa The LFS shall be fixed now.

**Comment by angelicaochoa** [comment]
@yichaoS 
Meta files that need to be regular "git" managed:

- [ ] all_phase2_target_2018_pub/all_phase2_target_2018_pub_meta_cna_hg19_seg.txt
- [ ] aml_target_2018_pub/aml_target_2018_pub_meta_cna_hg19_seg.txt
- [ ] blca_dfarber_mskcc_2014/meta_clinical_patient.txt
- [ ] blca_dfarber_mskcc_2014/meta_clinical_sample.txt
- [ ] brca_mbcproject_wagle_2017/brca_mbcproject_wagle_2017_meta_cna_hg19_seg.txt
- [ ] crc_msk_2018/meta_clinical_patient.txt
- [ ] crc_msk_2018/meta_clinical_sample.txt
- [ ] nbl_amc_2012/meta_clinical_patient.txt
- [ ] nbl_amc_2012/meta_clinical_sample.txt
- [ ] nbl_target_2018_pub/nbl_target_2018_pub_meta_cna_hg19_seg.txt
- [ ] nbl_ucologne_2015/meta_clinical_patient.txt
- [ ] nbl_ucologne_2015/meta_clinical_sample.txt
- [ ] nsclc_pd1_msk_2018/nsclc_pd1_msk_2018_meta_cna_hg19_seg.txt
- [ ] panet_shanghai_2013/meta_clinical_patient.txt
- [ ] panet_shanghai_2013/meta_clinical_sample.txt
- [ ] prad_p1000/prad_p1000_meta_cna_hg19_seg.txt
- [ ] sclc_cancercell_gardner_2017/sclc_cancercell_gardner_2017_meta_cna_hg19_seg.txt
- [ ] thyroid_mskcc_2016/meta_clinical_patient.txt
- [ ] thyroid_mskcc_2016/meta_clinical_sample.txt
- [ ] thyroid_mskcc_2016/meta_gene_matrix.txt
- [ ] thyroid_mskcc_2016/meta_timeline_status.txt

**Pull request merged**
