### PR TITLE
co-exp and enrichment tab in paad_qcmg_uq_2016

### PR DESCRIPTION
**Pull request by yichaoS**
Fix issue https://github.com/cBioPortal/datahub/issues/243

Renamed exp files into non-zscore. (They are not z-score files but somehow got named zscore)
The co-exp and enrichments tab are now presented. 
Triage testing instance: https://bit.ly/2FT97PJ

### CODE REVIEW

**Comment by yichaoS** [comment]
@jjgao The z-score profile somehow couldn't get generated because we don't have CNA data in this study (confirmed our script requires CNA data to allow calculation of zscore @angelicaochoa)

**Comment by jjgao** [comment]
@yichaoS @angelicaochoa we should allow z-scores file generation without CNA file. In that case, all samples will be used as the reference population. It was working that way.

**Comment by yichaoS** [comment]
Closing this one. Logged the "allow zscore generation without CNA" in a separate issue here: https://github.com/cBioPortal/datahub/issues/565

**Comment by yichaoS** [comment]
The co-exp and enrichment tabs are showing now, in both msk and public portal.
screen shot 2019-01-30 at 12 00 27 pm

**Pull request merged**
