### PR TITLE
Fix data_mutations_extended.txt in skcm_tcga

### PR DESCRIPTION
**Pull request by sandertan**
Remove '---' from Validation_Status and Validation_Method with:

```
cat data_mutations_extended.txt | awk -F '\t' -v OFS='\t' '{ if ($25 == "---") {$25 = ""}; if ($29 == "---") {$29 = ""}; print }' > data_mutations_extended_new.txt
mv data_mutations_extended_new.txt data_mutations_extended.txt
```

### CODE REVIEW

**Comment by sandertan** [comment]
This was suggested in https://github.com/cBioPortal/cbioportal/pull/2221

Validation report:
[Report_skcm.html.gz](https://github.com/cBioPortal/datahub/files/921887/Report_skcm.html.gz)

**Comment by pieterlukasse** [comment]
waiting for diff

**Comment by sandertan** [comment]
Added validation report created with cBioPortal 1.6.0, removed the old one.

**Comment by pieterlukasse** [comment]
Checked diff, looks good. Small sample of diff below:

image

**Pull request merged**
