### PR TITLE
Add published mutational signatures to pancan_pcawg_2020

### PR DESCRIPTION
**Pull request by MatthijsPon**
# What?
Add mutational signature contribution scores (published data) and mutational matrix (generated from data_mutations.txt) using SigProfilerMatrixGenerator (v1.2.15) to pancan_pcawg_2020. Includes README describing transformation.

Depends on this front-end PR: https://github.com/cBioPortal/cbioportal-frontend/pull/4540
Mutational signature tab will crash without it, as there is no p-value file included in the data.

Cancer studies updated in this pull request:
- pancan_pcawg_2020

# checks
For all pull requests:
- [X] Passes validation
- [x] Related PR merged

### CODE REVIEW

**Comment by ritikakundra** [comment]
@MatthijsPon can we get the reference for the mutational signature computing ?

**Comment by MatthijsPon** [comment]
@ritikakundra what reference exactly do you need? Do you want the script?
Contribution scores were calculated on a per-sample basis:
```contribution (signature x) = activity (signature x) / activity (all signatures)```
Mutational matrix was extracted using SigProfilerMatrixGenerator (v 1.2.15), which has it's own install function for reference genomes.

**Comment by rmadupuri** [comment]
PR STATUS: The data is being tested internally on our portal.

**Comment by inodb** [comment]
- [ ] The mutational signatures chart info tooltip does not give as much detailed info (there is more in the add charts dropdown):
image

**Review by rmadupuri — APPROVED** [review]

**Pull request merged**
