### PR TITLE
Normal leesix hsc 2018

### PR DESCRIPTION
**Pull request by stockschl**
# add Lee-Six 2018 HSC normal study to private cBioPortal

Cancer studies updated in this pull request: -

# checks
For all pull requests:
- [ ] Passes validation

For a new study (in addition to above):
- [ ] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [ ] is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [ ] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [ ] clinical sample and patient data with meta files
- [ ] mutations data with meta files
- [ ] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [ ] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

### CODE REVIEW

**Comment by rmadupuri** [comment]
@stockschl are these PR's ready for review?

**Comment by stockschl** [comment]
> @stockschl are these PR's ready for review?

@rmadupuri yes they are ready for review. Should I tick the boxes when creating the PR? If so - sorry I didn't do that yet!

**Comment by rmadupuri** [comment]
Nice! No worries the checklist is a bit outdated anyways. It would be helpful if you can add a README with the data transformation steps for reference as in https://github.com/cBioPortal/datahub/tree/master/public/aml_ohsu_2022. Its doesn't have to be this detailed though. Thanks @stockschl!

**Comment by stockschl** [comment]
> Nice! No worries the checklist is a bit outdated anyways. It would be helpful if you can add a README with the data transformation steps for reference as in https://github.com/cBioPortal/datahub/tree/master/public/aml_ohsu_2022. Its doesn't have to be this detailed though. Thanks @stockschl!

sure will do - Thank you @rmadupuri !

**Pull request closed without merging**
