### PR TITLE
Added case lists for pediatric_dkfz_2017

### PR DESCRIPTION
**Pull request by angelicaochoa**
Signed-off-by: Angelica Ochoa <aochoa4230@gmail.com>

### CODE REVIEW

**Comment by angelicaochoa** [comment]
@kalletlak Only one issue found - there weren't any case lists for study `pediatric_dkfz_2017` so I have added them myself

**Comment by angelicaochoa** [comment]
@pieterlukasse  looks like an issue here where if only case lists files are added then the validation tests fail. Can we override this behavior?

**Comment by pieterlukasse** [comment]
@angelicaochoa if you want to add an `_all` case list manually then you should turn off the setting that auto generates one (see in `meta_study.txt` ).  This is what is meant by the error

`Multiple case lists with this stable_id defined in the study | pediatric_dkfz_2017_all (already defined in meta_study.txt)`

**Comment by angelicaochoa** [comment]
@pieterlukasse fixed, thanks!

**Comment by jjgao** [comment]
@angelicaochoa @kalletlak were all samples profiled by whole exome or genome sequencing?

**Comment by pieterlukasse** [comment]
thanks @angelicaochoa . Perhaps now that you are at it, you could add a link to the original data as well? See how we did this for the TCGA provisional studies: https://github.com/cBioPortal/datahub/blob/rc/public/brca_tcga/meta_study.txt#L5

**Comment by angelicaochoa** [comment]
@pieterlukasse there's a pmid in the meta file so the frontend will automatically generate a link to the paper on the study view and study summary pages

**Comment by angelicaochoa** [comment]
@yichaoS @pieterlukasse updated branch

**Comment by angelicaochoa** [comment]
@pieterlukasse actually looks like the tests failed but not understanding why

**Comment by yichaoS** [comment]
@angelicaochoa it is related to a change in the testing script -- circle ci was not running at all actually. I'm asking @pieterlukasse 's help to fix it now.

**Comment by angelicaochoa** [comment]
@ritikakundra clinical file updates are checked in now

**Comment by angelicaochoa** [comment]
@pieterlukasse @sandertan okay there are still issues with this for some reason.

I added case lists, added changes from the sample clinical file that @ritikakundra made, and removed the global case list prop from the meta study. 

Ideas?

**Comment by sandertan** [comment]
Hi @angelicaochoa .

Validator report can be viewed under "Artifacts" tab on CircleCI. You have to expand the 'ERROR' branch. Direct link: https://295-63335718-gh.circle-artifacts.com/0/test-reports/ERRORS/pediatric_dkfz_2017-validation.html

For most of the errors, I have fixes ready in a PR. Will ask to merge it soon. 

This is a strange error. I think the length of the reference allele shouldn't be NA. If this data is missing, we might have to make the validator less strict. Could you take a look at this error?
screen shot 2018-07-03 at 19 28 28

**Comment by angelicaochoa** [comment]
@kalletlak can you look into the errors with the MAF [here](https://295-63335718-gh.circle-artifacts.com/0/test-reports/ERRORS/pediatric_dkfz_2017-validation.html) ?

**Pull request merged**
