### PR TITLE
add proteomics data from Nusinow et al. (2020) to CCLE 

### PR DESCRIPTION
**Pull request by SRodenburg**
Proteomics data was generated for various cell lines, in an extensive study (see https://gygi.hms.harvard.edu/publications/ccle.html for a summary).

Data was retrieved from here:
Sample Information: https://gygi.hms.harvard.edu/data/ccle/Table_S1_Sample_Information.xlsx
Proteomics data: https://gygi.hms.harvard.edu/data/ccle/protein_quant_current_normalized.csv.gz

- The values in the data represent protein abundance ratios relative to the abundance of reference proteins in "bridge samples". Bridge samples are not loaded.

I integrated this data into CCLE using the following transformation steps:

- Three samples were removed from the matrix (CAL120_BREAST_TenPx02, SW948_LARGE_INTESTINE_TenPx11 HCT15_LARGE_INTESTINE_TenPx30), because the cell lines involved multiple samples. These three cell lines were explicitly mentioned in the accompanied manuscript about the data, and the authors proposed to remove these if needed (see https://www.biorxiv.org/content/10.1101/2020.02.03.932384v1.full).
- The data had to be collapsed to per-gene values, the original data was per-protein. I used the Uniprot column and the Uniprot API to map protein IDs to NCBI Entrez IDs.
    - 2055 (16%) of the proteins could not mapped to NCBI entrez IDs, in which case I filled the blanks using the gene symbol which was already present in the original data.
    - 2130 (17%) of the proteins returned non-unique gene IDs, indicating that some proteins originated from the same gene. The duplicates were collapsed to per per-gene values by taking the average.
- I generated a matrix containing Z-scores derived from the log2-ratios per-gene. This enables the user to select protein abundance values as a separate profile from the query-by-gene interface in cBioPortal.
- I added some sample annotations to the clinical sample data indicating the 10-Plex ID and the TMT label.

### CODE REVIEW

**Comment by SRodenburg** [comment]
@rmadupuri I had to recreate this PR because there was something wrong in the git branch from the Hyve.

All changes from https://github.com/cBioPortal/datahub/pull/1433 are incorporated

**Review by rmadupuri — APPROVED** [review]

**Comment by Sjoerd-van-Hagen** [comment]
@rmadupuri  Hi Ramya,
This PR is merged by I do not see the data in the public portal yet. When will it be uploaded?

**Comment by rmadupuri** [comment]
Hi @Sjoerd-van-Hagen, there's been an issue with the public importer. @averyniceday is helping fix it. We will import the data soon as the fix is in.

**Comment by rmadupuri** [comment]
@Sjoerd-van-Hagen @SRodenburg, the data is available in the public portal now.

**Comment by Sjoerd-van-Hagen** [comment]
Great, thanks!

---

Sjoerd van Hagen

Team Lead cBioPortal & Open Targets

E ***@***.***

T *+31 30 700 9713*
W thehyve.nl <https://www.thehyve.nl/>


<https://www.linkedin.com/company/thehyve/>  <http://twitter.com/thehyvenl>
   <https://github.com/thehyve>

**Pull request merged**
