### PR TITLE
add study luad_cptac_2020

### PR DESCRIPTION
**Pull request by egarcialara**
# What?
- added new study [Michael A. Gillette et al. "Proteogenomic Characterization Reveals Therapeutic Vulnerabilities in Lung Adenocarcinoma" Cell 2020](https://www.cell.com/cell/fulltext/S0092-8674(20)30744-3)
https://github.com/cBioPortal/datahub/issues/1173

:information_source:  See [README](https://github.com/cBioPortal/datahub/blob/luad_cptac_2020/public/luad_cptac_2020/README.md) for transformation process

Cancer studies updated in this pull request:
- luad_cptac_2020

# checks
For all pull requests:
- [x] Passes validation

For a new study (in addition to above):
- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [x] is study meta data complete? e.g. pmid, group of PUBLIC
- [x] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [x] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [x] clinical sample and patient data with meta files
- [x] mutations data with meta files
- [x] MAF is based on hg19
- [ ] ~~MAF with 2 isoforms: uniprot and mskcc~~ _Not applicable_
- [x] CNA data with meta files
- [ ] ~~CNA segment data with meta files~~ _Not applicable_
- [x] Expression data including z-scores with meta files
- [x] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

Testing instance: 
https://triage.cbioportal.mskcc.org/study/summary?id=luad_cptac_2020

### CODE REVIEW

**Comment by yichaoS** [comment]
(a lot of overlap with ucec PR)

meta study

- remove `add_global_case_list`
- short name missing space `CPTAC Cell2020`

clincial data

- (to be confirmed with backend) `.` is not accepted as part of the sample ID.
- gender -> sex
- values of `cancer type` column should be `Non-Small Cell Lung Cancer`
- add `oncotree_code` column to clinical sample file and the values should be `LUAD`
- underscore should be removed from the clinical header first line (attribute name) for proper display.
-  there are (quote from paper) `102 paired NAT samples` matched normal samples, but in the somatic_status column there are only 97 with matched?

maf

- same question as the last point. in the "matched_normal_sample_barcode" column in the MAF all 104 samples seem to have an associated normal samples `-N`?

methylation:

- methylation data should be in expression-like format (https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#methylation-data) instead of generic essay, thus this profile should be viewed in plots/co-exp etc.

z score

- I want to confirm `data_protein_quantification_zscores_ref_diploid_samples.txt` and `data_mrna_seq_fpkm_zscores_ref_diploid_samples.txt` are against all diploid samples and not all samples? We don't have a script to generate against all diploid samples (the ones existed are directly from firehose/legacy TCGA) and I don't see it provided in publication. Or is this zscore data downloaded somewhere?

**Comment by yichaoS** [comment]
@egarcialara @SRodenburg 

Pushed a few more small changes (for importing purpose) 
- renamed the mrna files (checked with publication and your Readme, it should be RPKM not FPKM) 
- renamed miRNA case list (mirna -> miRNA, so the importer could recognize it)
- added sample counts to case lists' description
- renamed mutation file

**Review by yichaoS — APPROVED** [review]

**Comment by yichaoS** [comment]
@egarcialara I'm doing a final check of a study with the paper. Looking at this graph about data statistics, I noticed a few of the data files we have here seems short for a few hundred records, comparing to the paper graph. Just want to ask you to confirm, from the 
Screen Shot 2021-11-09 at 11 01 41 PM

- 31964 data_mutations.txt   
- 12722 data_methylation_epic.txt
- 17335 data_mrna_seq_rpkm.txt 
- 10317 data_protein_quantification.txt 

I then looked into supplemental table S2C and I do see 16,478 records there for methylation as the paper stated.
Could you please check the other 3 profiles?

**Comment by egarcialara** [comment]
Hi @yichaoS,
When reading the files, the 4 of them have the number of rows stated in the paper figure. I checked this again just now.
For different reasons, the files I uploaded have a lower number of rows. 
- In the mutations data file, I removed 382 rows for which the mapping from hg19 to hg38 coordinates wasn't found with LiftGenome, and 96 rows were duplicated because they had two amino acid conversions.
- In the methylation, RNA-seq and protein data files, I removed the rows where Hugo_Symbol, Entrez_Gene_Id or Composite.Element.REF was either empty or duplicated.

Hope that's alright!

**Comment by yichaoS** [comment]
> Hi @yichaoS, When reading the files, the 4 of them have the number of rows stated in the paper figure. I checked this again just now. For different reasons, the files I uploaded have a lower number of rows.
> 
> * In the mutations data file, I removed 382 rows for which the mapping from hg19 to hg38 coordinates wasn't found with LiftGenome, and 96 rows were duplicated because they had two amino acid conversions.
> * In the methylation, RNA-seq and protein data files, I removed the rows where Hugo_Symbol, Entrez_Gene_Id or Composite.Element.REF was either empty or duplicated.
> 
> Hope that's alright!
> 
> PD. The original data from the UCEC and PAAD studies also satisfies the number of features mentioned in the paper / LinkedOmics.

@egarcialara For methylation & RNA-seq, we can do either Hugo_Symbol or Entrez_Gene_Id; they don't have to present the same time. If there are rows removed for this reason could you add them back? Otherwise this study should be ready to be merged now. (cc' @ritikakundra @SRodenburg)

**Comment by egarcialara** [comment]
Hi @yichaoS ,
I made a new commit with the methylation and rna seq tables containing all original rows (16478 and 18099, respectively), without removing NAs or duplicates for `Hugo_Symbol` or `Entrez_Gene_Id`.

**Pull request merged**
