### PR TITLE
New public study: ihch_ismms_2015

### PR DESCRIPTION
**Pull request by yichaoS**
# What?
Chol cohort: Sia paper 
Publication link: https://www.nature.com/articles/ncomms7087#Ack1

Cancer studies updated in this pull request:
- ihch_ismms_2015

# Data Included
- clinical data: no clinical data provided in supp, only added oncotree code, sample type, sample class
- fusion data: Table S1
- mutation data: Table S5 (S6, S7, S8 included in S5)
-- Tool Used to backtrack from protein change to chromosomal start and stop position:
https://bioinformatics.mdanderson.org/transvar/

# Issues
RNA-seq: 
- deposited in the GEO database (GSE63420) 
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE63420

MAF:
- Can't find any intel data in table S5 "We identified 237 alterations in the coding regions including 229 mutations affecting 209 genes (range 18–53, average 30 per tumour) and eight insertions and deletions (indels; Supplementary Fig. 4, Supplementary Table 5)."
- 11 mutations not annotated (altho if query GN API directly you get results - e.g. http://annotation.genomenexus.org/hgvs/7:g.121943711A%3EC?isoformOverrideSource=mskcc&cancerHotspots=summary)
See file: https://github.com/cBioPortal/datahub/blob/ihch_ismms_2015/public/ihch_ismms_2015/unannotated.txt
- 18 consequence unmatched (all have protein change in supp but after our annotation there's intron/IGR). See file: https://github.com/cBioPortal/datahub/blob/ihch_ismms_2015/public/ihch_ismms_2015/protein_change_unmatched.txt
- 75 protein change unmatched (only position shifted, amino acid is the same, for example, `D533A -> D245A`). See file: https://github.com/cBioPortal/datahub/blob/ihch_ismms_2015/public/ihch_ismms_2015/protein_change_unmatched.txt 

# Triage testing instance
http://triage.cbioportal.org/triage/study/summary?id=ihch_ismms_2015

Validation is not passed because of the unannotated variants

# checks
For all pull requests:
- [x] Passes validation

For a new study (in addition to above):
- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [x] is study meta data complete? e.g. pmid, group of PUBLIC
- [x] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [x] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [ ] clinical sample and patient data with meta files
- [x] mutations data with meta files
- [x] MAF is based on hg19
- [x] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [x] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

### CODE REVIEW

**Comment by ritikakundra** [comment]
@yichaoS is there a link to review?

**Comment by yichaoS** [comment]
@ritikakundra The PR is not for review yet. I'm just creating it so me and @sbabyanusha can consolidate files.

**Review by ritikakundra — COMMENTED** [review]
meta-study description has a weird character in it
We should reach out to ask for clinical data

**Comment by ritikakundra** [comment]
@yichaoS where is the file with the unannotated variants?

**Review by rmadupuri — APPROVED** [review]

**Pull request merged**
