### PR TITLE
nsclc_tracerx_2017: Added ctDNA samples to the cohort from Abbosh et al. Nature 2017 paper.

### LINKED ISSUE #980: Abbosh et al. Phylogenetic ctDNA analysis depicts early-stage lung cancer evolution. Nature 2017.
It seems that the patients are included in https://www.cbioportal.org/study/clinicalData?id=nsclc_tracerx_2017. Should we just curate this dataset into the nsclc_tracerx_2017 cohort?

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

### PR DESCRIPTION
**Pull request by rmadupuri**
# What?
Fix #980 

Cancer studies updated in this pull request:
- nsclc_tracerx_2017

Updates Made:
- [x] MAF (Uniprot, mskcc isoforms)
- [x] Clinical 
- [x] Meta Data 
- [x] Case lists

Testing Instance: https://triage.cbioportal.mskcc.org/study/summary?id=nsclc_tracerx_2017

# checks
For all pull requests:
- [ ] Passes validation

For a new study (in addition to above):
- [ ] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [ ] is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [ ] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [ ] clinical sample and patient data with meta files
- [ ] mutations data with meta files
- [ ] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [ ] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

### CODE REVIEW

**Comment by sbabyanusha** [comment]
@rmadupuri:

- [ ] Can we add (No. of samples sequenced) to the meta_mutations_extended.txt file.

- [ ] Can we rename the KI_67 column header to KI67_PERCENTAGE and add a description to KI67?

**Comment by yichaoS** [comment]
clinical files
- typo: `Lymph Node   Invovlement`
- translate `0/1` in `Recurrence or Death` to actual text values
- `MORE_2SNV_CFDNA` and `LNI` and `Adjuvent Treatment` and `HISTOLOGY` camel case values
- no oncotree code, cancer type, cancer type detailed assigned to ctDNA samples?
- post-ctDNA are shown first in patient view sample listing (see screenshot 1)
- Isn't ctDNA sample have a different color as dots in patient view?
- `Ubiquitous Assay  Panel` should be `NUMBER` type?
- possible to combine this two columns `Recurrence or death` and `Time_to_recurrence_or_death (months)` to make DFS survival curves? (see screenshot 2, from the paper)
- same columns to make into timeline `status`?
- possible to make tableS10 seg file? Tho mean seems to be missing. Didn't look deep.


Screen Shot 2020-05-05 at 3 01 18 AM

Screen Shot 2020-05-05 at 3 25 19 AM

meta files
- reorganize language of this part of meta study `pre- and postoperative ctDNA sequencing of 96 and 24 samples from 100 NSCLC TRACERx patients.` into something a bit more clear like: `  ... (what kind of?) sequencing of ctDNA samples of pre 96 and 24 post...early stage NSCLC....`
- meta study short name swap words order -> NSCLC (Tracerx 2017)
- (Already mentioned by @sbabyanusha) better description in meta mut
- all case lists files seems to have different `name` and `description` as other case lists (which we normalized recently)

**Comment by rmadupuri** [comment]
@yichaoS @BabyASatravada Thanks for the review. The study is updated except for the two points.
- For ctDNA sequencing, each patient has a separate assay panel to target SNV's observed in the corresponding tumors. Included this in the meta description. The SNV's specific to each panel is not mentioned in the paper. 
- Table 3 is for metastatic/relapse samples. We have added only ctDNA samples from Abbosh et al, since its not clear for patient CRUK0063 which are autopsy and non autopsy samples from supplementary Table 4 (RegionSum).

**Comment by rmadupuri** [comment]
Hi @jjgao, can we get a final review of this study if possible? Please find the testing instance here: https://triage.cbioportal.mskcc.org/study/summary?id=nsclc_tracerx_2017
Thanks!

**Comment by jjgao** [comment]
- [ ] Is it possible to get allele frequencies or ccf?

- [ ] is there timeline data?

- [ ] Can we map the histology to detailed oncotree_code?
image

- [ ] Performance Status: what do 0/1 mean?
image

- [ ] What is lymph node involvement? Metastatic disease in LN?
image

- [ ] Is there a WDG field and vocabulary defined by the FACETS integration effort? If so, we should use the same one.
image

- [ ] Add an attribute to indicate which are pre- or post-operative
image

- [ ] wondering if we have a defined vocabulary for "smoking history"? If not, maybe worth to go through all studies and normalize them.
image

- [ ] Is it necessary to have both attributes of `STAGE` and `TUMOT_STAGE`? Do we usually use `TUMOT_STAGE` or `TUMOR_STAGE_2009` in other studies? also the vocabulary may be different. Again, maybe worth to go through all studies and normalize them.
image

- [ ] Why are there more than 2 mutations when I select no?
image

**Comment by rmadupuri** [comment]
Thanks for the review @jjgao. Updated the study. 
1. Is it possible to get allele frequencies or ccf?
Done
2. Is there timeline data? 
This figure: https://www.nature.com/articles/nature22364/figures/4 from paper shows timeline for 8 patients. But we don't have the complete data given. Will contact the author.
3. Is there survival data?
We have only RFS
Screen Shot 2020-06-09 at 5 38 12 PM
4. Can we map the histology to detailed oncotree_code? 
Done. We don't have the oncotree codes for `Lung Carcinosarcoma` and `Lung Invasive adenocarcinoma` so kept the histology attribute for now until the codes are added.
5. Performance Status: what do 0/1 mean?
It's `ECOG Performance Status`. Updated the attribute name.
6. What is lymph node involvement? Metastatic disease in LN?
Could not infer if its regional/met LN from paper. The description given was `Lymphnode involvement noted on pathological specimen`
7. Is there a WDG field and vocabulary defined by the FACETS integration effort? If so, we should use the same one.
Confirmed with Avery. The WDG vocabulary in facets just says Yes, No or NA. I think we should keep the vocabulary of this study since it says clonal/subclonal GD?
8. Add an attribute to indicate which are pre- or post-operative
Done.
9. wondering if we have a defined vocabulary for "smoking history"? If not, maybe worth to go through all studies and normalize them.
Will create a new issue to normalize this attribute.
10. Is it necessary to have both attributes of STAGE and TUMOT_STAGE? Do we usually use TUMOT_STAGE or TUMOR_STAGE_2009 in other studies? also the vocabulary may be different. Again, maybe worth to go through all studies and normalize them.
Removed the duplicated STAGE attribute
11. Why are there more than 2 mutations when I select no?
The attribute `More than 2 SNVs detected in cfDNA` is specific to cfDNA SNV count. Since the mutation count is for all samples we have removed this attribute since this might be confusing.

**Pull request merged**
