### PR TITLE
Lift coordinates in brain_cptac_2020 

### PR DESCRIPTION
**Pull request by egarcialara**
# What?
Lift coordinates from hg38 to hg19, using UCSC LiftGenome.

- Files modified: `data_mutations.txt` (Start Position, End Position and NCBI_Build), and `meta_study.txt` (reference_genome).
- Original data: 10114 rows. Uploaded data: 9951 rows (88 removed as there was no match in the lift to hg19, 75 removed by maf2maf, 45 belong to mitochondrial genome)

Cancer studies updated in this pull request:
- brain_cptac_2020 

# checks
For all pull requests:
- [x] Passes validation

### CODE REVIEW

**Comment by yichaoS** [comment]
@egarcialara is it re-annotated?

**Comment by egarcialara** [comment]
Hi @yichaoS ,
Thank you for the review.
I uploaded a new `data_mutations.txt`, re-annotated with maf2maf. I do not see many changes in the alleles, including the one you mentioned (ATAD3A). Please let me know if I'm missing something.
Besides, I removed a few rows that were mitochondrial DNA, as they'd yield an error in the maf2maf re-annotation. If you'd like to see them included, let me know and I can put them back in. (The numbers are in the top comment)

**Comment by yichaoS** [comment]
@egarcialara Please ignore my last comment. The allele is correct and I'm running another round of annotation. We can leave the mitochondrial rows out.

**Review by yichaoS — APPROVED** [review]

**Comment by yichaoS** [comment]
@egarcialara actually could you please put those mitochondrial rows back? The portal would automatically ignore those rows when importing. It is good to have the datafile itself complete tho.

**Comment by egarcialara** [comment]
Good idea, done!

**Pull request merged**
