### PR TITLE
glioma_mskcc_2019: new study

### PR DESCRIPTION
**Pull request by rmadupuri**
Cancer studies updated in this pull request:
- glioma_mskcc_2019

Testing instance: https://triage.cbioportal.mskcc.org/study/summary?id=glioma_mskcc_2019

# checks
For all pull requests:
- [x] Passes validation

For a new study (in addition to above):
- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [x] is study meta data complete? e.g. pmid, group of PUBLIC
- [x] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [x] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [x] clinical sample and patient data with meta files
- [x] mutations data with meta files
- [x] MAF is based on hg19
- [x] MAF with 2 isoforms: uniprot and mskcc
- [x] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [x] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

### CODE REVIEW

**Comment by rmadupuri** [comment]
@ritikakundra @yichaoS this study is ready for review. The data is taken from the publications supplementary tables https://clincancerres.aacrjournals.org/content/25/18/5537.  However, there are few variants and timeline records that do not have start / stop positions or dates. I have separated them to `time_line_with_no_start_and_stop_dates.txt` and `variants_with_no_positions.txt` files. Should this data be backfilled from impact study(there is no direct mapping in few cases) How should we go about this?

**Comment by yichaoS** [comment]
from QC: 
- [ ] add sample counts into MAF meta description
- [ ] add LICENSE
- [ ] add gene panel readme
- [ ] possibility of translate `progress free` into `disease free`? So the DFS curve can show? Not sure.
- [ ] `N/A` to `NA` in `MGMT_STATUS` attribute
- [ ] confirm if CNA is sequenced from the same panel as mutations
- [ ] should we keep the genome nexus header in the MAF?

**Comment by rmadupuri** [comment]
@yichaoS updated the study here: https://github.com/cBioPortal/datahub/pull/1046

For, 
point 4, there is a cbioportal issue to support the PFS K-M plot. We can have the data as is.
point 6, CNA is sequenced from the same panel as maf.
point 7, I think we should have the genome nexus header since it adds the version number?

**Comment by ritikakundra** [comment]
- [ ] Add PMID
- [ ] OncoKB Levels check
- [ ] Normalize Camel case for all attributes
- [ ] What are the patients with NOTES, I don't see any?

**Comment by rmadupuri** [comment]
@ritikakundra added the updates here: https://github.com/cBioPortal/datahub/pull/1048

**Pull request merged**
