### PR TITLE
new study: cfDNA MSKCC 2019

### LINKED ISSUE #1000: Razavi et al. High-intensity sequencing reveals the sources of plasma circulating cell-free DNA variants. Nature Medicine. 2019.
https://www.nature.com/articles/s41591-019-0652-7?proof=true

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

### PR DESCRIPTION
**Pull request by yichaoS**
# What?
Fix #1000 
New study: cfDNA, MSKCC, Nature Medicine 2019
Publication Link: https://www.nature.com/articles/s41591-019-0652-7?proof=true#Sec32
Triage Instance Link: https://triage.cbioportal.mskcc.org/study/summary?id=cfdna_mskcc_2019

# Data curated
### Mutation data 
   - from "supplemental tables" section
   - somatic mutation only
   - 124 cfDNA samples (T11), removed all 'W' samples (controls/healthy)
   - 124 tumor samples (T13)

Q: do the extra columns need to be included?

### Clinical data
   - TMB & Tissue: "source data" section, fig. 3a 
   - MSI score: "source data" fig. 3d    
   - Age: "source data" fig. 5b
   - other attributes' values are filled based on understanding of paper content

Q: can't find the values for SAMPLE_TYPE('metastasis/recurrence/primary') for NSCLC and CRPC
Q: not sure how to define oncotree code here for MBC and CRPC (filled in CT/CTD with values from the paper, don't want to lose these values by just using BREAST, which will overwritten CTD by importer)

### gene matrix
   - from paper content

Q: tho GRAIL has 508 genes, only the intersection w/ IMPACT410 is looked at afterwards, should we only include the 410 genes in the GRAIL panel? " For the purpose of comparison with tumor biopsies, only variants mapping to the intersection of the 410 genes present in the two gene panels were considered."

# Checks
For all pull requests:
- [ ] Passes validation
(not passed yet because new gene panel is not manually imported to portal portal yet; need to decide that genes included in that panel)

For a new study (in addition to above):
- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [x] is study meta data complete? e.g. pmid, group of PUBLIC
- [x] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [x] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [x] clinical sample and patient data with meta files
- [x] mutations data with meta files
- [x] MAF is based on hg19
- [x] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [x] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

### CODE REVIEW

**Comment by yichaoS** [comment]
@ritikakundra Questions from the previous QC: 
- clinical point 2: not sure where to put `Advanced untreated or progressive metastatic` since we may not want to lose that information. Also what is the appropriate ONCOTREE code to use here?
- clinical point 3: not sure if `Castration-resistant prostate cancer` is just about disease progression. But same question as point 2. 
- MAF: table 6 is only for oncogenic variants, and only contain ~120 variants out of ~4000. Also I think CH variants should be included but if not, not sure how to filter them.

**Comment by ritikakundra** [comment]
@yichaoS please add the triage link to this

**Comment by ritikakundra** [comment]
- This is not just a cfDNA study, we are showing tumor and cfdna samples so title and description should change. WBC is being treated as matched normal for both types so do we need that in the title?
- We can add breast and prostate for the NA samples (BREAST and PROSTATE)
- Can we add more data from table 3 in clinical

**Comment by rmadupuri** [comment]
@ritikakundra are we including the clonal hematopoiesis variants as well? 

Re: The cfDNA variants (Table 11) also contains variants from clonal hematopoiesis (compare to the source data from extended Fig 8). Should the CH variants be considered? If not, should the Supp Table 6 be used instead of Table 11?

**Comment by yichaoS** [comment]
@rmadupuri: table 6 is only for oncogenic variants, and only contain ~120 variants, compare to the total 4000 they reported.

**Comment by yichaoS** [comment]
@ritika addressed all the points. (except update meta study with WBC being the normal for all samples. I checked again seems like tumor samples have their own regular normals). 
@rmadupuri addressed all points (except which table to use for MAF as we discussed yesterday)

**Comment by inodb** [comment]
Thanks for working on this 🙏 !

I'm not entirely sure what we should do with clonal hematopoiesis mutations e.g. DNMT3A, PPM1D (see [Figure 4d](https://www.nature.com/articles/s41591-019-0652-7/figures/4?proof=true)). Are we filtering those out for MSK-ACCESS? I don't see them for instance for MSK-ACCESS. This might be a broader discussion tho about how we should handle it in cBioPortal but just FYI. I think it's fine to list them like this for now, for people familiar with this type of date it will be obvious that it's CH. They do all nicely roll out of the cfDNA vs tissue comparison: https://triage.cbioportal.mskcc.org/comparison/mutations?sessionId=5e6a3ebde4b0fc5db534eafa

**Comment by inodb** [comment]
Another discussion point: it's a bit tricky to do things like: "find me all cases that have no matching mutations in tissue and cfDNA". What I do now is to look at the genomic evolution tab's heatmap and look at each case one by one

**Comment by rmadupuri** [comment]
@yichaoS @ritikakundra should we change the study name? since `cfDNA (MSKCC 2019)` doesn't follow our naming convention?

**Comment by yichaoS** [comment]
@ramya The two attributes values indeed are very similar, but they are not identical if looking at the data files. Also the definition given in the publication of the two attributes are different as well: "The mean coverage of   all baits in the experiment after collapsing and stitching". So I think we should keep them separate.

**Comment by yichaoS** [comment]
@inodb Presumably we could have a pre-made case list including the cases with no matching, or define a clinical attribute to use for filtering; but it requires a lot of manual work for curations to go through each cases, so unfortunately it is not feasible at the moment. It would be ideal if this is an automatic feature.

**Pull request merged**
