### PR TITLE
prad_tcga: recalculated expression zscores

### LINKED ISSUE #597: missing MYC expression values from TCGA provisional prostate adenocarcinoma dataset mRNA matrix downloaded
Reported by [a user](https://groups.google.com/d/msg/cbioportal/0HkH6zstJqk/hAmldcVXBQAJ)

z-scores are missing for all samples except one in prad_tcga

> Thanks for your e-mail. I have been able to extract the files. However, looking at the RNA Seq Z score file, there are no values for Myc except for 1 patient. I do not understand this when a graph can be drawn to show the correlation of BRF1 and MYC in TCGA provisional prostate adenocarcinoma dataset.
What I want to be able to do is calculate the p value for the Pearson correlation - although a pearson correlation coefficient is stated on the co-expression graph, the p value stated is for the Spearman correlation.
Does this make sense??? To be able to do the calculation, I need to be able to download the MYC expression values which I think should be there if a graph can be drawn???

### PR DESCRIPTION
**Pull request by rmadupuri**
# What?
Related issue #597

### CODE REVIEW

**Comment by rmadupuri** [comment]
@ritikakundra calculating the zscores using the new script restored the missing MYC expression values (also few other genes). Since we are now calculating zscores independent of sample diploid status, the mean and std of the genes change and hence the zscores change from what we saw earlier. Is that alright?  Should we go ahead and recalculate the zscores for all studies? Thanks.

**Comment by jjgao** [comment]
Thanks, @rmadupuri . I think we should recalculate z-scores for all studies. 

I also think it's better to calculate zscores after log transformation for rnaseq data, but one complication is that there are negative data in pancancer datasets (due to batch correction). I am not sure how to should handle that...

**Comment by n1zea144** [comment]
I guess ignoring negative data is out of the question?

**Comment by jjgao** [comment]
@n1zea144 We could reset small (negative numbers or very small positive numbers). Maybe for this round, let's not worry about it, ie. keep it the same as before?

In the long run, we should support better/more rna data transformations: https://github.com/cBioPortal/cbioportal/issues/5528

**Pull request merged**
