### PR TITLE
Updates to tcga (adding seg files) and metabric

### PR DESCRIPTION
**Pull request by zheins**
@jjgao @pieterlukasse 

This PR addresses the missing seg data in the tcga public studies, as well as an update to the METABRIC study.

### CODE REVIEW

**Comment by pieterlukasse** [comment]
@pulyakhina : can you please help us test this one?

**Comment by pulyakhina** [comment]
@pieterlukasse you mean only brca_metabric.tar.gz or all studies in this commit?

**Comment by pieterlukasse** [comment]
@pulyakhina preferably all, but starting with TCGA

**Comment by pulyakhina** [comment]
@zheins @pieterlukasse skcm has the same error as previously which (as far as I understand) I can't fix myself:

`ERROR: data_mutations_extended.txt: lines [39182, 39183, 39184, (238 more)]: column 16: Sample ID not defined in clinical file; value encountered: 'TCGA-D9-A4Z6-01'`

**Comment by pieterlukasse** [comment]
@zheins I tested all studies in this PR using latest hotfix + fixes in https://github.com/cBioPortal/cbioportal/pull/1866 and https://github.com/cBioPortal/cbioportal/pull/1868. Most of the studies pass validation, but 6 still fail. Here is my summary. 

#### Studies that pass validation (26 in total):

'acc_tcga'
'brca_tcga'
'chol_tcga'
'coadread_tcga'
'dlbc_tcga'
'esca_tcga'
'gbm_tcga'
'hnsc_tcga'
'kich_tcga'
'kirc_tcga'
'laml_tcga'
'lgg_tcga'
'lihc_tcga'
'luad_tcga'
'lusc_tcga'
'meso_tcga'
'ov_tcga'
'paad_tcga'
'pcpg_tcga'
'prad_tcga'
'sarc_tcga'
'stad_tcga'
'thym_tcga'
'ucec_tcga'
'ucs_tcga'
'uvm_tcga'

#### Studies that are still failing: 

1. blca: issue in validator code for segments file. **We** will make a fix in the validation script. 
2. cesc: issue in validator code for segments file. **We** will make a fix in the validation script.
3. kirp: attribute TUMOR_TYPE is found in patient file while it should be in sample file. We could try to move this to the sample file. @zheins : can you also check how much effort this would be? 
4. skcm: errors in mutation data file. Solution: to be decided
5. tgct: attribute TUMOR_TYPE is found in patient file while it should be in sample file. We could try to move this to the sample file. @zheins : can you also check how much effort this would be? 
6. thca: 2 missing files regarding mRNA data. Solution: @zheins : can you please add these missing files?

**Comment by sandertan** [comment]
@zheins I tested the brca_metabric, and it is missing some files:
```
DEBUG: meta_CNA.txt: Starting validation of meta file
ERROR: meta_CNA.txt: Missing field 'data_filename' in meta file

DEBUG: meta_expression.txt: Starting validation of meta file
ERROR: meta_expression.txt: Missing field 'data_filename' in meta file

DEBUG: meta_mutations_extended.txt: Starting validation of meta file
ERROR: meta_mutations_extended.txt: Missing field 'data_filename' in meta file

ERROR: -: Cancer type needs to be defined for a study. Verify that you have a study file and have defined the cancer type correctly.
ERROR: -: No valid study file detected
Validation of study failed.
```

**Comment by sandertan** [comment]
Made fix for: 
1. blca: issue in validator code for segments file. We will make a fix in the validation script.
2. cesc: issue in validator code for segments file. We will make a fix in the validation script.
in https://github.com/cBioPortal/cbioportal/pull/1873

**Comment by pieterlukasse** [comment]
@zheins On OV study I found some strange sample ids at the end of the file, like so: 

```
TCGA-13-0800    TCGA-13-0800-10 cd5a08e6-343a-494e-b73a-2b060c33451d    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] NO      [Not Available] [Not Availab
TCGA-13-0801    TCGA-13-0801-01 dfaf19b4-03b4-49d3-b39f-01aaeb897a2a    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] 0.6     NO      1.5     [Not Available] [Not Availab
TCGA-13-0801    TCGA-13-0801-10 d2c929db-171c-4b5c-9de5-613407999d56    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] NO      [Not Available] [Not Availab
TCGA-13-0802    TCGA-13-0802-01 9e78346d-14d1-4c3e-a144-5b90c32a2731    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] 1.1     NO      1.4     [Not Available] [Not Availab
TCGA-13-0802    TCGA-13-0802-10 c1ab65a8-155e-40dc-a2ae-d526e0ee5138    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] NO      [Not Available] [Not Availab
TCGA-13-0803    TCGA-13-0803-01 13227d89-2bd2-4775-80a5-3fc08927dd25    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] 0.9     NO      1.3     [Not Available] [Not Availab
TCGA-13-0803    TCGA-13-0803-10 81bdc7f0-3cbf-4965-976d-6fb3bd080d72    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] NO      [Not Available] [Not Availab
TCGA-13-0804    TCGA-13-0804-01 7432f954-a16f-4053-bedd-aa776f939f71    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] 1.3     NO      1.5     [Not Available] [Not Availab
TCGA-13-0804    TCGA-13-0804-10 47946a17-b529-4490-894b-e74baf6beb3c    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] NO      [Not Available] [Not Availab
TCGA-13-0805    TCGA-13-0805-01 01cd17b5-aa30-4a47-a1c5-501f9aedb3d2    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] 0.8     NO      1       [Not Available] [Not Availab
TCGA-13-0805    TCGA-13-0805-10 49ad654d-d1de-4cf8-a689-9193bb0926db    [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] [Not Available] NO      [Not Available] [Not Availab
TCGA-10-0931-01A-21     TCGA-10-0931-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-42-2582-01A-21     TCGA-42-2582-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-61-2610-01A-21     TCGA-61-2610-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-13-0901-01A-21     TCGA-13-0901-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-13-1411-01A-21     TCGA-13-1411-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-42-2589-01A-21     TCGA-42-2589-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-36-2552-01A-21     TCGA-36-2552-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-13-1410-01A-21     TCGA-13-1410-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-36-2540-01A-21     TCGA-36-2540-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-04-1341-01A-21     TCGA-04-1341-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-24-1416-01A-21     TCGA-24-1416-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
TCGA-42-2591-01A-21     TCGA-42-2591-01A-21-20  NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
```
So the last samples contain much longer part of the "barcode" (and actually do not comply to the TCGA barcode format...) and potentially overlap with samples in previous lines, given data loader will only use the first part of the barcode, i.e. only `TCGA-42-2591-01` portion of `TCGA-42-2591-01A-21`)

**Comment by sandertan** [comment]
Issue with skcm study:
https://github.com/cBioPortal/datahub/issues/4

**Comment by pieterlukasse** [comment]
@zheins @n1zea144 I think this is almost ready to merge. The fastest way to merge this is to perhaps move out the problematic studies and solve them in another PR while we merge the successful ones.

**Comment by zheins** [comment]
@sandertan I fixed the metabric issues and moved the column 'TUMOR_TYPE' from the patient file to the sample file in kirp and tgct. I also added data_RNA_Seq_v2_mRNA_median_Zscores.txt to thca. I didn't see another missing file.

 @pieterlukasse I fixed those extra samples from the end of the samples clinical file in the ov study.

**Comment by sandertan** [comment]
@zheins Great! I tested and reviewed the krip, tgct and thca studies and they all pass validation on the current cBioPortal hotfix branch with PR 1866! I have a couple points that I think we should address before we merge.

- [ ] The other missing file for the thca study is the meta file for `data_RNA_Seq_v2_expression_median.txt`. Will you be able to add it?
- [ ] Is the update on the OV study coming up later? Didn't find it in your latest commit.
- [ ] I also tested the BRCA Metabric study, which still gives quite some errors. I attached the report. But because it's not a TCGA study, it has less priority for us. We can also remove this study from this PR and put it in a new PR, so that we can merge the good TCGA studies.
[Report_brca_metabric.html.zip](https://github.com/cBioPortal/datahub/files/608700/Report_brca_metabric.html.zip)
- [ ] The only remaining TCGA study with errors is the skcm study.

**Comment by sandertan** [comment]
@zheins I found another issue with the studies. 4 types of meta files are currently missing, and therefor the corresponding data files cannot be loaded. I wonder if you have time to also add those. Thanks!

- [ ] data_clinical_supp_oncotree.txt
- [ ] data_gistic_genes_amp.txt
- [ ] data_gistic_genes_del.txt
- [ ] data_mutsig.txt

**Comment by jjgao** [comment]
@zheins @pieterlukasse @sandertan: Does this pull request introduce any new issues -- issues that do not exist in the current files? If not, we should merge this pull request and log the issues and fix them later.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao Sander indicated no new issues were introduced so please merge.

@sandertan could you log tickets for the remaining issues?

**Pull request merged**
