### PR TITLE
tcga data fixes

### PR DESCRIPTION
**Pull request by zheins**
Fixes for issues #17 #18 and #24.

@pieterlukasse @n1zea144 @sandertan

### CODE REVIEW

**Comment by Sjoerd-van-Hagen** [comment]
Hi Zack,

Thanks for looking into this.

@oplantalech or @sandertan can one of you review on Monday?

**Comment by sandertan** [comment]
Thanks @zheins I'll test it tomorrow.

**Comment by sandertan** [comment]
Hi @zheins, thanks for the update! I've ran validateData.py on all updated studies, and it seems you solved a lot of the previous issues, but I've encountered a couple new ones.

Solved:
- Missing CANCER_TYPE_DETAILED in tcga studies? #17
- Missing meta files in TCGA (Provisional) studies #18
    - meta_clinical_supp_oncotree.txt
    - meta_gistic_genes_amp.txt
    - meta_gistic_genes_del.txt
    - meta_mutsig.txt
- z-score file missing for `mrna` profile #24

Issues that have to be solved before merging:
- [ ] `uvm_tcga.tar.gz` seems to be damaged, I can't decompress it.
- [ ] `acc_tcga` has an issue in the second line in data_bcr_clinical_data_sample.txt. It seems a space instead of a tab is seperating 'Vial Number' and 'Oncotree code'
- [ ] For all studies, `meta_clinical_supp_oncotree.txt` can be removed. I see that you merged `data_clinical_supp_oncotree.txt` in `data_bcr_clinical_data_sample.txt`, so `meta_clinical_supp_oncotree.txt` is not necessary any more.

Issues that can be solved in other PR:
- [ ] `prad_tcga` has an issue in the segment file:
  - Line number: 89752, Error: Start position of segment is greater than end position, Found: 102493076-102129460
  Quick fix: Maybe we can exchange these two numbers with each other, or remove the line.
- [ ] Error in `skcm_tcga` #4
  - I've made a PR to change `validateData.py` https://github.com/cBioPortal/cbioportal/pull/2221 to solve 2 of the 3 errors.
  - "Sample ID not defined in clinical file (TCGA-D9-A4Z6-01)"
  - What is 'data_mutations_annotated.txt'? It doesnt have a meta-file.
- [ ] Missing metafiles in `thca_tcga` #28
  - Can you take a look at this? Might be an easy fix.

I attached the HTML reports, generated with cBioPortal 1.5.0.
[PR31_reports.tar.gz](https://github.com/cBioPortal/datahub/files/892662/PR31_reports.tar.gz)

**Comment by zheins** [comment]
@sandertan everything should be fixed except "Sample ID not defined in clinical file" occurs 241 times. We can address that in a separate PR.

**Comment by sandertan** [comment]
@zheins Thanks, this fixes most of the issues! Could you take a look at these remaining ones (some new):

- [ ] `aac_tcga` Unfortunately the error in line 2 is still in. I verified that I was using the updated file (Modified April 5th).
screen shot 2017-04-07 at 11 06 54

- [ ] `skcm_tcga` The 5th line (Containing the clinical attribute) is not tab-seperated but contains `[',]`.
```
#Patient Identifier	Sample Identif	
#Identifier to uniquely specify a pati
#STRING	STRING	STRING	STRING	NUMBER	
#1	1	1	1	1	
['PATIENT_ID', 'SAMPLE_ID', 'OTHER_SAM
TCGA-BF-A1PU	TCGA-BF-A1PU-01	D9C812
TCGA-BF-A1PU	TCGA-BF-A1PU-10	A4D739
```

- [ ] `prad_tcga` still has an issue in the segment file:
screen shot 2017-04-07 at 11 20 24

- [ ] `thca_tcga` The only file that is missing a meta file is `data_rppa_Zscores.txt`.

- [ ] `thca_tcga` There's a problem with `data_methylation_hm450.txt`. The validator crashes with a python error: `_csv.Error: line contains NULL byte`. Also, it crashes in VIM and I can't open it in sublime/openoffice.

If these are solved, I think we can merge :)

**Comment by zheins** [comment]
@sandertan I addressed the issues above.

**Comment by sandertan** [comment]
Hi @zheins thanks for the update and adding the CPTAC data! We're almost there:

- [ ] `thca_tcga` Could you add the meta file for `data_rppa.txt` please?
- [ ] `skcm_cga` Unfortunately the line with Attributes (line 5) was not written to `data_bcr_clinical_data_sample.txt`
screen shot 2017-04-10 at 11 17 55

**Comment by zheins** [comment]
I fixed the issues mentioned above except for the mass spec data problems. lets put that in a separate pr. @sandertan

**Comment by sandertan** [comment]
I'll move the remaining issues with the mass spectrometry data files to a new issue.

**Comment by sandertan** [comment]
I validated and importer all the studies, and most studies load without errors.

- For the `skcm_tcga` study a change to the validator is required to load the mutation file, which I added to https://github.com/cBioPortal/cbioportal/pull/2221
- For the `brca_tcga, coadread_tcga and ov_tcga` studies, a change to the validator is required to load the mass spectrometry files: https://github.com/cBioPortal/cbioportal/pull/2310
- The `coadread_tcga and ov_tcga` studies have errors in data files: https://github.com/cBioPortal/datahub/issues/32

This PR can be merged while we solve #32 in a new PR.

**Pull request merged**
