### PR TITLE
added mutation packager info to meta mut files for all 31 provisional…

### PR DESCRIPTION
**Pull request by yichaoS**
… studies

### CODE REVIEW

**Comment by angelicaochoa** [comment]
@yichaoS can you remove the package type references? (type: raw, type: regular)

**Comment by yichaoS** [comment]
@angelica i removed the types. Just curious -- what do those types mean?

**Comment by angelicaochoa** [comment]
@yichaoS Changes look good. Want to rebase and then I'll merge?

**Comment by yichaoS** [comment]
@angelicaochoa Thanks Angelica. It's in sync with the current rc now.

**Pull request merged**
