### PR TITLE
New Study Curation : brca_smc_2018

### PR DESCRIPTION
**Pull request by sbabyanusha**
Github issue : https://github.com/cBioPortal/datahub/issues/373

Article Curated: https://www.ncbi.nlm.nih.gov/pubmed/29713003

We have the following data available in the paper for this study.

- [x] Clinical
 Supplemental Table 1
- [x]  MAF 
 Supplemental Table 6

Triage Instance:
http://triage.cbioportal.mskcc.org/study/summary?id=brca_smc_2018

# checks
For all pull requests:
- [x] Passes validation

For a new study (in addition to above):
- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [x] is study meta data complete? e.g. pmid, group of PUBLIC
- [x] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [ ] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [x] clinical sample and patient data with meta files
- [x] mutations data with meta files
- [x] MAF is based on hg19
- [x] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [x] Expression data including z-scores with meta files
- [x] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

Some issues remained
- TCGA samples for comparison are not included from the cohort
- TCGA barcodes ends with `-01A`, `-01B`
- mutsig data missing gene symbol
- need to email author for RNA-seq & CNA data & weather to include the BRCA1&BRCA2 germline

### CODE REVIEW

**Comment by rmadupuri** [comment]
@yichaoS @sbabyanusha thank you for adding the study. A few comments below:
1. BRCA1/BRCA2 germline mutations are given in Supplementary Table4. Since they are publicly available, should we add them?
2. MutSig data is available in Supp Table7. Can it be added as well? (SMC mutations alone)
3. The study description says 187 samples are whole exome sequenced and the paper says `186 tumor/normal matched samples from whole exome sequencing and 168 samples (168 tumors with 10 normals) from whole transcriptome sequencing`. Should the description and sequenced case list be updated?
4. Can RNA-seq data be added as well? I think it is available here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE113184 see the supplementary file `GSE113184_expression_tpm.txt.gz` (The file also contains 10 normal samples).
5. Can we also add `Sequencing platform` clinical attribute? 
6. Looks like CNA is analyzed but the data is not available.

**Comment by sbabyanusha** [comment]
Thank you for the review @rmadupuri . Updated the study.
1. For comments 1 and 6 we have emailed the author for `CNA and germline mutations`. (For germline mutations even though it is available in  public we just wanted to confirm with the author before adding it).
2. `Mutsig` is not in our format.(Bases covered column `N` is missing)
3. @yichaoS said that `BR065` is the sample which is not WES-ed in the clinical file. As this sample does have mutation data as well, @yichaoS removed it from the `seq case list and meta_mut.`
4. Added the expression data.
5. As all the samples are now `WES sequenced` we didn't add the clinical attribute. 
All the changes have been updated to the triage instance.

**Comment by rmadupuri** [comment]
Thanks for the changes @sbabyanusha @yichaoS. Two issues that I missed earlier.
1. The study name is missing the journal.
2. RNA-Seq case list is missing.

I still see the old description for the study. Maybe the changes are not pushed through? Otherwise, the triage instance looks good to me!

**Comment by yichaoS** [comment]
@ramya 
- We did include the institution in the study name as in our file format. Please review this chapter here: https://github.com/cbioportal/cbioportal/blob/master/docs/File-Formats.md#cancer-study
- The exp data is TPM format so the case list couldn't be generated.

**Pull request merged**
