### PR TITLE
New public study: Chronic Lymphocytic Leukemia 

### PR DESCRIPTION
**Pull request by Rima-Waleed**
# checks
For all pull requests:
- [ ] Passes validation

For a new study (in addition to above):
- [ ] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [ ] is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [ ] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [ ] clinical sample and patient data with meta files
- [ ] mutations data with meta files
- [ ] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [ ] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

### CODE REVIEW

**Comment by Rima-Waleed** [comment]
Files to be added (pending from authors): 
- [ ] CNA
- [ ] RNA Seq

**Comment by sbabyanusha** [comment]
Thanks for adding this @Rima-Waleed. We can improve the dataset a bit more. See below.

**Meta study:**
1. Rewrite the study description to our standard. (Include sequencing  platform information)
2. Include sequencing  platform information.

**Clinical:**
1. Update Cohort attribute --> Center
2. What is IGHV? (Add description)
3. Update IGHV_IDENTITY_% --> IGHV_IDENTITY_PERCENTAGE
4. Add Sequencing platform Information --> WXS,WGS,RNA Seq,RRBS)* Available in Supp.TabLE 1.
5. Add M-CLL,U-CLL WES columns.
6. Add additional clinical attributes from Supp.Table 1 and also in https://cllmap.org/viz/swimmer-plot/
7. 6 Patients has 2 samples each. According to the supp file. 
8. The germline analysis was done in the paper.

|  Sample 1   | Sample 2 | 
| ----------- | --------- |
| CRC-0035 | DFCI-5088 | 
| DFCI-5053 | CRC-0020 | 
| DFCI-5170  | CRC-0011       | 
| DFCI-5193 | CRC-0007 | 
| JB-0010 | CRC-0009 | 
| NHLBI-0052 | NHLBI-0073 | 

**Methylation:**
1. Add Methylation 450K data.

**RNA Seq:**
1. RNA Sequencing data is available in https://cllmap.org/index.html

**Timeline Treatment Data:**
1. data is available in https://cllmap.org/viz/swimmer-plot/

- [ ] NOTCH1 % seems to be very low in the portal when compared to the paper. (5% in the portal vs 12.3%) Can we check why?
- [ ] Looks like they have carried out Targeted sequencing as well.

**Comment by ritikakundra** [comment]
- [ ] description numbers don't match portal numbers which don't match the paper
- [ ] Only 85% of samples were sequenced? Not all?
- [ ] What does additional samples mean?
- [ ] There are a lot of attributes which don't make sense or are very genomic. Can you revisit what should be pulled as clinical
- [ ] RNA Seq data?
- [ ] What about WES data?
- [ ] Age at reference sample?
- [ ] what is IGHV identity? Why is not a number?
- [ ] FFS should be a KM plot
- [ ] what is time zero on timeline?
- [ ] Mutsig data?
- [ ] What MAF was used for these samples?

**Comment by ritikakundra** [comment]
- [ ] The paper is Nature Genetics not Nature
- [ ] Should we change the title to MBN since it consists of both samples?
- [ ] No matched normals?
- [ ] Not sure I understand the sample count:  1,095 patients with CLL and 54 patients with monoclonal B cell lymphocytosis (MBL) from which whole-exome sequencing (WES) or whole-genome sequencing (WGS) (n = 1,074), RNA-sequencing (RNA-seq) (n = 712) and DNA methylation data (n = 999) were analyzed---> We only are showing WGS data? But we are showing more than 1074 samples. And no WES data?
- [ ] Can we get more info for when the survival data was recorded from?

**Comment by ritikakundra** [comment]
One final check on if the genomic data was properly mapped.

**Pull request closed without merging**
