### PR TITLE
Add CircleCI validation to validate studies on cbioportal.org with Datahub

### PR DESCRIPTION
**Pull request by sandertan**
Implemented @jjgao 's idea from #350 . This will be checked weekly only in datahub/master.

Test result:
```
cbioportal.org contains studies which are not on cBioPortal Datahub:
cll_iuopa_2015
gbm_tcga_pub2013
hcc_msk_venturaa_2018
hnc_mskcc_2016
lusc_tcga_pub
mixed_allen_2018
sarc_mskcc
stad_tcga_pub

cBioPortal Datahub contains studies which are not on cbioportal.org:
hnc_mskcc_2014
```

### CODE REVIEW

**Comment by pieterlukasse** [comment]
great idea!

**Comment by yichaoS** [comment]
@sandertan @jj by next Wednesday we shall have the 8 missing studies back on datahub. I'll remove hnc_mskcc_2014

**Comment by jjgao** [comment]
@sandertan cool.

**Comment by sandertan** [comment]
Can we merge this one?

**Comment by yichaoS** [comment]
@sander could you update the branch? Also I noticed under the master branch, the readme already contains icon to show the result of this test?

**Comment by sandertan** [comment]
@yichaoS Rebased on master. Yes, the current icon displays the result of validating all studies.

**Pull request merged**
