### PR TITLE
New Release July: Add studies to datahub

### PR DESCRIPTION
**Pull request by sbabyanusha**
Cancer studies updated in this pull request:
- nbl_msk_2023 - https://www.cbioportal.org/study/summary?id=nbl_msk_2023
- bladder_mskcc_2022 - https://www.cbioportal.org/study/summary?id=bladder_mskcc_2022
- luad_mskcc_2023_met_organotropism - https://www.cbioportal.org/study/summary?id=luad_mskcc_2023_met_organotropism
- aml_ohsu_2022 - https://www.cbioportal.org/study/summary?id=aml_ohsu_2022
- stmyec_wcm_2022 - https://www.cbioportal.org/study/summary?id=stmyec_wcm_2022
- coad_silu_2022 - https://www.cbioportal.org/study/summary?id=coad_silu_2022
- bowel_colitis_msk_2022 - https://www.cbioportal.org/study/summary?id=bowel_colitis_msk_2022

## 📇  Data Improvement
   * Pan-can studies methylation addition: methylation profile 450K is added to all 32 TCGA Pan-Can studies, in generic assay format. Data source: [GDC](https://gdc.cancer.gov/node/977). https://private.cbioportal.mskcc.org/study/summary?id=acc_tcga_pan_can_atlas_2018
   * Pan-can studies Ancestry addition: Genetic Ancestry data is added to all 31 TCGA Pan-Can studies, in generic assay format. Data source: [GDC](https://gdc.cancer.gov/about-data/publications/CCG-AIM-2020). https://private.cbioportal.mskcc.org/study/summary?id=acc_tcga_pan_can_atlas_2018

### CODE REVIEW

**Comment by rmadupuri** [comment]
**nbl_msk_2023:**

- Discrepancy in p/s counts. Paper: 283p/470s, Portal: 176p/223s
- From Supplemental Table1, Sequencing type - MSK-IMPACT : 223s, WGS: 37s, WGS+RNA-seq: 210s. Are we releasing only the IMPACT sequenced samples? Can we reach out to the authors for WGS, RNA-seq data? 
- There's additional clinical data in Supp Table 1
- Mutational signatures data avail for WGS samples in Supp Table 1
- There is treatment timeline data for this study. See [Fig6](https://www.nature.com/articles/s41588-023-01395-x/figures/6) and https://papaemmelab.github.io/neuroblastoma-clonality-viewer/. Can we request that?
- Update the title from `Neuroblastoma Clinical Sequencing Cohort (MSK, Nat Genet 2023)` -> `Pediatric Neuroblastoma (MSK, Nat Genet 2023)`  and Include the matched normal status in the study description
- Can we normalize the sample type values to `Primary`, `Metastasis` or `Recurrence`? Column Y of Supp Table 1 has the data.
- Is the Age at Diagnosis from birth? And can we change this from Months to Years?

**Review by rmadupuri — CHANGES_REQUESTED** [review]
Thanks so much Anusha! I think we can enhance the studies a bit more. See below

**nbl_msk_2023:**

- Discrepancy in p/s counts. Paper: 283p/470s, Portal: 176p/223s
- From Supplemental Table1, Sequencing type - MSK-IMPACT : 223s, WGS: 37s, WGS+RNA-seq: 210s. Are we releasing only the IMPACT sequenced samples? Can we reach out to the authors for WGS, RNA-seq data? 
- There's additional clinical data in Supp Table 1
- Mutational signatures data avail for WGS samples in Supp Table 1
- There is treatment timeline data for this study. See [Fig6](https://www.nature.com/articles/s41588-023-01395-x/figures/6) and https://papaemmelab.github.io/neuroblastoma-clonality-viewer/. Can we request that?
- Update the title from `Neuroblastoma Clinical Sequencing Cohort (MSK, Nat Genet 2023)` -> `Pediatric Neuroblastoma (MSK, Nat Genet 2023)`  and Include the matched normal status in the study description
- Can we normalize the sample type values to `Primary`, `Metastasis` or `Recurrence`? Column Y of Supp Table 1 has the data.
- Is the Age at Diagnosis from birth? And can we change this from Months to Years? 
- Private cBio link has been included in the paper https://cbioportal.mskcc.org/study/summary?id=nbl_msk_2023 for data availability :( 

**bladder_mskcc_2022:**
- Can we update the study id from `bladder_mskcc_2022` to `bladder_msk_2022`. I think we planned on using MSK instead of MSKCC in the study ID, names etc., to be consistant. I don't see the study was referenced in the paper should be ok to update?
- Do the `Sample Class` values correspond to the Sample IDs - For ex, sample [SCBO-11_Parental](https://triage.cbioportal.mskcc.org/patient?studyId=bladder_mskcc_2022&caseId=SCBO-11) shows as `Xenograft` but is that the parental tumor? It is not clear which of these samples are `parental tumors`, `organoids`, `xenografts` or 
`xenoderivedLines`
- The study description says 130 tumor/normal pairs
- Normalized expression data is available at https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE103990

**coad_silu_2022:**
- Also has 16S rRNA microbiome, cna segment data at https://figshare.com/articles/dataset/Supplementary_Data_AC-ICAM/16944775
- TP53 percentage of alterations is higher in portal - 43% vs. paper - 36% (see Fig3c)
- Matched normal status in the description and somatic_status attribute to clinical.
- We can prolly convert the GSVA data as generic assay for now.

**bowel_colitis_msk_2022:**
- We can remove the timeline data - only status track for 3 patients avail
- MSI Score -> NUMBER, Tumor Purity -> NUMBER
- Does 1 in `Lung FSM` mean `Yes`? If so, can we convert all the FSM attributes to a STRING?
- case lists are missing 1 sample (179 vs 180 cohort size). Is that right?
- Add WES and FoundationOne samples to gene panel matrix
- matched normal status to description

**luad_mskcc_2023_met_organotropism:**
- study ID doesn't follow our conventions but the link is already published in the paper. 
- add matched normal status for WES samples (all samples had normals) and in the description
- TableS5 has mutational signatures data for IMPACT and WES samples. 
- Can we request the timeline data from the authors? The ever Met Site and Months to met can be converted to timeline as well. 

**aml_ohsu_2022:**
- Missing Somatic Status attribute

**stmyec_wcm_2022:**
- Case lists names to our conventions
- More patient data can be added from https://molecularcasestudies.cshlp.org/content/8/7/a006227/T2.expansion.html
- structural variant were analyzed but no data avail in paper. Reach out to the authors?

**Methylation and Ancestry**:
- Can the Data Source and Transformation steps be added to the individual study README as in https://github.com/cBioPortal/datahub/tree/master/public/blca_tcga_pan_can_atlas_2018#readme for reference?

**Comment by sbabyanusha** [comment]
nbl_msk_2023:

- The author mentioned that they cannot share WGS and RNA-Seq data due to lack of patient cosent.
- Mutational signatures data avail for WGS samples in Supp Table 1 - reached out to author
- There is treatment timeline data for this study. See [Fig6](https://www.nature.com/articles/s41588-023-01395-x/figures/6) and https://papaemmelab.github.io/neuroblastoma-clonality-viewer/. Can we request that? - reached out to author
- 
bladder_mskcc_2022:

- Can we update the study id from bladder_mskcc_2022 to bladder_msk_2022. I think we planned on using MSK instead of MSKCC in the study ID, names etc., to be consistant. I don't see the study was referenced in the paper should be ok to update?- Cannot rename the study as we have another study with bladder_msk_2022.

- Do the Sample Class values correspond to the Sample IDs - For ex, sample [SCBO-11_Parental](https://triage.cbioportal.mskcc.org/patient?studyId=bladder_mskcc_2022&caseId=SCBO-11) shows as Xenograft but is that the parental tumor? It is not clear which of these samples are parental tumors, organoids, xenografts or xenoderivedLines - waiting for the author to respond on this confusion with normalization as they didnt provide anything in the publication.

coad_silu_2022:

- TP53 percentage of alterations is higher in portal - 43% vs. paper - 36% (see Fig3c) - figured out there was something wrong in the publication as both the source and the data we have are exactly same.

bowel_colitis_msk_2022:

- Add WES and FoundationOne samples to gene panel matrix - Need to add FoundationOne panel

**Comment by ritikakundra** [comment]
https://triage.cbioportal.mskcc.org/study/summary?id=nbl_msk_2023

- Why is this added, "https://triage.cbioportal.mskcc.org/study/summary?id=nbl_msk_2023"
- What does Sample Code mean? The text is not normalized
- Neuroblastoma Clinical Sequencing Cohort does not follow our nomenclature

https://triage.cbioportal.mskcc.org/study/summary?id=bladder_mskcc_2022

- The cohort description does not signify matched normals even though somatic status is 100% matched
- There is all this additional clinical data in the paper Table 1. Summary of Patient-Derived Bladder Tumor Organoid Lines and Corresponding Clinical Data that can be added.
- There are discrepancies between https://triage.cbioportal.mskcc.org/results?cancer_study_list=bladder_mskcc_2022&tab_index=tab_visualize&case_set_id=bladder_mskcc_2022_all&Action=Submit&gene_list=TERT%250AKDM6A%250ACDKN2AP14ARF%250ACDKN2AP16INK4A%250AFGFR3%250AKMT2C%250AKMT2D and Fig2. Are they the same platforms?

https://triage.cbioportal.mskcc.org/study/summary?id=coad_silu_2022

- We can expand to Clinical M Stage, Clinical N Stage etc.
- History of Cancer: Yes*, what does * mean?
- Samples with frameshift mutations don't have VAFs. Can we check why?

https://triage.cbioportal.mskcc.org/study/summary?id=bowel_colitis_msk_2022

-Remove religion
- Salicylates has a Y?
- Low tumor content has 1 and Na values...needs more explanation 
- Clinical data needs a little cleaning

https://triage.cbioportal.mskcc.org/study/summary?id=luad_mskcc_2023_met_organotropism

- The description needs to have the text we have standardized. 
- Some clinical attributes have _ in them and are upper case
- The paper says, "In this study, we examined 2,532 primary and metastatic LUAD specimens from 2,309 patients, using manually reviewed clinicopathological data, including [treatment](https://www.sciencedirect.com/topics/medicine-and-dentistry/therapeutic-procedure) context, and tumor genomic information obtained from a combination of broad-panel targeted [DNA sequencing](https://www.sciencedirect.com/topics/medicine-and-dentistry/dna-sequencing) and whole-exome sequencing (WES)." This is not true in the portal.

https://triage.cbioportal.mskcc.org/study/summary?id=aml_ohsu_2022

- "" in the titles of some clinical attributes as well as data 
- The description says 500 matched normals but somatic status says 100% matched normals?

https://triage.cbioportal.mskcc.org/study/summary?id=stmyec_wcm_2022

- Tumor type should be Sample Type
- Should reach out for SV data cos just the abstract talks about it

**Comment by sbabyanusha** [comment]
https://www.cbioportal.org/study/summary?id=nbl_msk_2023 
- Remove this statement from the study description: Due to lack of patient consent to data sharing, raw data for WGS and RNA-seq tumors are not available in this cohort. - **This is to clarify question3.**
- Why does our sample count not match what is described in the paper abstract? “Here, using genomic profiling of 470 sequential and spatially separated samples from 283 patients." - **the author is not ready to share the WGS and RNA-Seq data due to lack of patient access and so our portal count doesn't match with the data.**

https://www.cbioportal.org/study/summary?id=luad_mskcc_2023_met_organotropism
- WES samples missing structural variants and copy number? Explanation from Author: They didn't clean the calls. 
- Need assay indicator for each sample (Which version of IMPACT or WES) 

Screen Shot 2023-08-08 at 3 38 47 PM

https://www.cbioportal.org/study/summary?id=aml_ohsu_2022
- Why does the study include samples without any molecular data? For example aml_ohsu_2022_2038 - **This sample is profiled for  rna-seq data.** 

https://www.cbioportal.org/study/summary?id=coad_silu_2022
- Are we really missing mutation data for 67 samples? Or did they simply have no mutations? - Only 281 tumors were sequenced for WES

https://www.cbioportal.org/study/summary?id=bowel_colitis_msk_2022
- Same question, why are there so many samples without mutation and copy-number data? - **14 cases didn't have any calls. confirmed from the source.**

**Pull request merged**
