### PR TITLE
utuc_gaby_2020

### PR DESCRIPTION
**Pull request by nobie666**
# What?
Fix # .

Cancer studies updated in this pull request: List of somatic mutations identified in the whole-exome sequencing of upper-tract urothelial carcinomas (n = 30).
- a
- .

# checks
For all pull requests:
- [ ] Passes validation

For a new study (in addition to above):
- [ ] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [ ] is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [ ] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [ ] clinical sample and patient data with meta files
- [ ] mutations data with meta files
- [ ] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [ ] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

### CODE REVIEW

**Review by nobie666 — COMMENTED** [review]
List of somatic mutations identified in the whole-exome sequencing of upper-tract urothelial carcinomas (n = 30).

**Comment by nobie666** [comment]
Dear administrator, 
our paper is accepted in Genome Biology. We would like to include the link for the data on UTUC in the manuscript that the researchers can access too. Would you think possible to get the data approved by the end of the week to have the link. If anything further is needed or missed, please let us know. Best. Professor Gabriel Malouf

**Comment by ritikakundra** [comment]
@nobie666 can you add unzipped files?

**Comment by nobie666** [comment]
Sorry for this inconvenience. We have attached two .txt files containing mutation MAF file and mutation meta file. Please let me know if you need anything else.

**Comment by ritikakundra** [comment]
@nobie666 Thanks for the update. We are annotating the MAFs with our annotators but can you add a data_clinical_sample.txt file also which could be as simple as a PATIENT_ID, SAMPLE_ID, CANCER_TYPE, CANCER_TYPE_DETAILED, and SOMATIC_STATUS (which is to define if a sample has a matched normal or not)

**Comment by nobie666** [comment]
Thank you so much for handling our data. I just uploaded another two files according to your message. please let me know if you need anything else. Best, Gabriel Malouf

**Comment by ritikakundra** [comment]
@nobie666 Should we push this to the public portal or do you want to keep this under permission access?

**Comment by nobie666** [comment]
Yes, please help us to push this to the public portal soon, thank you very much!

**Comment by ritikakundra** [comment]
@nobie666 The study is in the public portal: https://www.cbioportal.org/study/summary?id=utuc_igbmc_2021

**Pull request closed without merging**
