### PR TITLE
new study: gbm_columbia_2019

### LINKED ISSUE #741: Zhao et al. Immune and genomic correlates of response to anti-PD-1 immunotherapy in glioblastoma. 2019
https://www.ncbi.nlm.nih.gov/pubmed/30742119

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

### PR DESCRIPTION
**Pull request by yichaoS**
# What?
Fix #741 
Link to publication: https://www.nature.com/articles/s41591-019-0349-y
Link to Triage Instance: https://triage.cbioportal.mskcc.org/study/summary?id=gbm_columbia_2019

# Data curated
- Clinical: Supplementary Tables 1
- MAF: Supplementary Tables 2
- Timeline: Supplementary Tables 1 (PD1 Inhibitor related)

# checks
For all pull requests:
- [x] Passes validation

For a new study (in addition to above):
- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [x] is study meta data complete? e.g. pmid, group of PUBLIC
- [x] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [x] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [x] clinical sample and patient data with meta files
- [x] mutations data with meta files
- [x] MAF is based on hg19
- [x] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [x] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

### CODE REVIEW

**Comment by jjgao** [comment]
- [ ] Convert "Dead" and "OS from Dx" to OS_Status and OS_Months
- [ ] Convert "Dead" and "OS from PD1 Inhibitor" to OS_from_PD1i_Status and OS_from_PD1i_Months
image
- [ ] Is it possible to make pfs_status and pfs_months?
image
- [ ] What is "KPS at PD1 Inhibitor Start"? add descrption.
image
- [ ] What does "PD1 inhibitor" mean (please add description)? Should the type be String? Should we change the value to Yes and No?  
image
- [ ] meaning of 0 and 1
image
image
- [ ] I think we should remove the dates or convert them into timeline?
image
- [ ] #VALUE!
image

**Comment by yichaoS** [comment]
@ramya I would keep ` Should we remove the additional OS Fom PD1 Inhibitor since we have OS from Dx is given.` since it is originally given in supplemental and maybe people do want to look at the OS this way in a pie chart, since it is an important indicator, instead of just having it in the survival plot.

**Comment by yichaoS** [comment]
reply @jjgao comments

- Not sure what 0/1 mean for first recurrence (either 0 or 1 has positive number of NUMBER_OF_PRIOR_RECURRENCES in the next column) 

- removed `Date of Death` and Can `Date of PD or last date MRI without PD if no PD` be used as the stop date in timeline? Does PD means PD1 here? If not, we are thinking of removing it.

**Comment by yichaoS** [comment]
@jjgao @rmadupuri 
The rest are all fixed. (see some screenshots of PFS curve & timeline for various events: death, progression, treatment).
Screen Shot 2020-04-28 at 5 26 18 PM
Screen Shot 2020-04-28 at 5 27 11 PM

**Comment by ritikakundra** [comment]
@yichaoS @sbabyanusha:

- Can we rename the attributes like (Steroids During PD1 Inhibitor) Drug Name- Drug Name (Steroids During PD1 Inhibitor)?
- 
- For KPS >/= 70=1, <70= 0: can this be renamed to KPS since the data is already in the range format and not 0 and 1?
- 
- Paper primarily describes samples as responders and non-responders. Do we have that for the cohort?
- 
- For some reason, some patients are showing deceased dot and some are not.
- https://triage.cbioportal.mskcc.org/patient?sampleId=gbm_columbia_2019_102&studyId=gbm_columbia_2019
- 
- https://triage.cbioportal.mskcc.org/patient?sampleId=gbm_columbia_2019_100&studyId=gbm_columbia_2019
- 
- What is the date 0 for OS and timelines?

**Comment by yichaoS** [comment]
reply @ritika comments  
- The responders and non-responders are reflected in the supplemental file as `response` with `yes/no` as values, and we included it in our clinical data as is. (see screenshot)
Screen Shot 2020-05-04 at 3 12 42 PM

- The 0 points for OS and timelines, and all date related values are date of diagnosis.

**Comment by ritikakundra** [comment]
@yichaoS Looks good. 

@inodb : Wanted to check this issue with you. We have cases for this study wherein some patients we see the deceased dot on the timeline and for some, we don't :

- https://triage.cbioportal.mskcc.org/patient?sampleId=gbm_columbia_2019_102&studyId=gbm_columbia_2019
- https://triage.cbioportal.mskcc.org/patient?sampleId=gbm_columbia_2019_100&studyId=gbm_columbia_2019

Is that a bug or a rule in place?

**Pull request merged**
