### PR TITLE
Public release studies

### PR DESCRIPTION
**Pull request by Rima-Waleed**
Cancer studies updated in this pull request:

| Study_ID                       | Testing Instance Link         | Sample Count|
| -- | -- | -- |
|ptad_msk_2024         | https://www.cbioportal.org/study/summary?id=ptad_msk_2024 | 104 Samples |
| plmeso_msk_2024        | https://www.cbioportal.org/study/summary?id=plmeso_msk_2024 | 14 Samples |
| pancan_mappyacts_2022       | https://www.cbioportal.org/study/summary?id=pancan_mappyacts_2022 | 788 Samples |
| cscc_ranson_2022      | https://www.cbioportal.org/study/summary?id=cscc_ranson_2022 | 25 Samples |
|mbn_msk_2024 | https://www.cbioportal.org/study/summary?id=mbn_msk_2024  | 396 Samples |
|ucec_msk_2024 | https://www.cbioportal.org/study/summary?id=ucec_msk_2024  | 33 Samples |
| hcc_clca_2024 | https://www.cbioportal.org/study/summary?id=hcc_clca_2024 | 494 Samples |
| brca_fuscc_2020 | https://www.cbioportal.org/study/summary?id=brca_fuscc_2020 | 69 Samples |
| gist_msk_2023 | https://www.cbioportal.org/study/summary?id=gist_msk_2023 | 469 Samples |
| mixed_msk_tcga_2021 | https://www.cbioportal.org/study/summary?id=mixed_msk_tcga_2021 | 19 Samples |
| |  | 2,411 Samples |

### CODE REVIEW

**Comment by Rima-Waleed** [comment]
@jjgao review comments:

- ptad_msk_2024: I noticed that CDSI data elements were included. Were they used in the publication? What's the general guideline/policy when to release CDSI data?
- lms_msk_2024: Is there any reason the germline mutations were not added into the mutations profile?
- lms_msk_2024: some patients have extremely long survival. Please double check.
- lms_msk_2024 & gist_msk_2023: was institute source used in the paper?
- ucec_msk_2024: not sure how other studies are using this field, but maybe we could standardize this one? E.g. MSI_Status with High/Intermediate/Low values.
- lms_msk_2024 & gist_msk_2023: what's the reference of age for lms_msk_2024? How do we normalize them between studies?
- gist_msk_2023: Ethnicity categories do not look standard
- mixed_msk_tcga_2021: msk P- ids were not used for msk patients and TCGA IDs were also changed
- mixed_msk_tcga_2021: no CNA profile but CN segment data was included.
- pancan_mappyacts_2022: there was 0 CNA events. Please double check.
- pancan_mappyacts_2022: sequenced samples without mutations should have mutation_count of 0
- name convention of pancen: mixed_msk_tcga_2021 & pancan_mappyacts_2022. I think pancan is less confusing than mixed
- pancan_mappyacts_2022: is it possible to get the RNA data?
- cscc_ranson_2022: TMB is extremely high (a log higher than [other CSCC studies](https://www.cbioportal.org/study/summary?id=cscc_dfarber_2015%2Ccscc_hgsc_bcm_2014%2Ccscc_ucsf_2021)). It may be real - it seems like all have high UV signatures? But I think we need to review the data further. 
- cscc_ranson_2022: they only report 5 SBS mutational signatures. Would that create any confusion interpreting the data?
- hcc_clca_2024: is it possible to include the ecDNA amplified genes?
- hcc_clca_2024: fusion data is kinda messy, e.g. [redundant events and events missing partners](https://cbioportal.mskcc.org/patient?studyId=hcc_clca_2024&caseId=CLCA_0002)...
- brca_fuscc_2020: what does the acronyms of TNBC subtypes means?

**Comment by Rima-Waleed** [comment]
Thanks for the thorough review @jjgao @schultzn, 

All comments have been addressed; some notes below:

ptad_msk_2024:

- CDSI elements were not used in the publication, however the author confirmed they are fine to keep in the study


lms_msk_2024: 
- study will not be released at the moment, survival data needs to be revised with the author 

gist_msk_2024: 
- confirmed age is age at diagnosis and institute source removal

ucec_msk_2024: 
- MSI comment field is removed, only releasing MSI type/score

mixed_msk_tcga_2021: 
- Authors don’t have the ID mapping (for MSK samples), hence MSK-xx format is used to match the paper. TCGA IDs are updated
- Name convention: this is an old study and using ‘mixed’ was agreed upon a couple of years ago.
- CNA profile pending author response

pancan_mappyacts_2022: 
- CNA events are seen in public portal (link added in PR)

cscc_ranson_2022: 
- TMB scores were re-calculated and confirmed to be high by the paper; confirmed high UV signatures (ID13 mutational signature) causes high mutation count and so high TMB
- Mutational signatures data removed until we clarify it wouldn’t cause confusion in interrupting the results

hcc_clca_2024: 
- SV data had redundant and events missing partners due to intergenic events so data removed and author contacted for correct format.
- ecDNA data pending author response.

Missing/additional data types:
- Authors contacted and data addition is pending their response (ecDNA & SV for hcc_clca_2024, CNA for mixed_msk_tcga_2021)

**Comment by jjgao** [comment]
Thanks, @Rima-Waleed! 

Two follow-up comments.

- for [ptad_msk_2024](https://cbioportal.mskcc.org/study/summary?id=ptad_msk_2024), are you ok to release CDSI data even though they didn't use the data? @schultzn 
- for cscc_ranson_2022, I am not sure if there were germline mutations. e.g. in [MUC16]
(https://cbioportal.mskcc.org/results/mutations?cancer_study_list=cscc_ranson_2022&tab_index=tab_visualize&case_set_id=cscc_ranson_2022_all&Action=Submit&gene_list=ABCA13%250AMUC16%250ATTN%250ACSMD3%250ACOL6A5%250AMUC12%250AAHNAK%250ATP53&mutations_gene=MUC16). Wondering if we should hold this study for review?

**Comment by schultzn** [comment]
We should only release additional CDSI data if it was used in the manuscript - for this study and all future studies. 

Not sure I understand the germline comment ... are there germline mutations publicly released with the study? And if so, are they useful, or mostly benign SNPs?

**Review by jjgao — APPROVED** [review]

**Comment by jjgao** [comment]
> We should only release additional CDSI data if it was used in the manuscript - for this study and all future studies.

Confirmed that CDSI data has been removed from the study.

> Not sure I understand the germline comment ... are there germline mutations publicly released with the study? And if so, are they useful, or mostly benign SNPs?

@schultzn and I took a look at the mutations and germline mutations seemed to be filtered out.

**Pull request merged**
