### PR TITLE
Adding public studies

### PR DESCRIPTION
**Pull request by zheins**
Public studies from cbioportal.org (114 total)

### CODE REVIEW

**Comment by zheins** [comment]
@jj renamed the tcga studies and moved into the public directory. The tcga dir still contains the pathology reports.

**Comment by jjgao** [comment]
Thanks, @zheins! If it is easy, could you rename tcga_coadread.tar.gz to coadread_tcga.tar.gz, etc to match the study IDs?

**Comment by pieterlukasse** [comment]
:+1:  thanks @zheins ! Does this contain the cptac data as well?

**Comment by zheins** [comment]
@pieterlukasse good point - no this does not have the cptac data. If we want to just get this merged I can put that in a separate PR.

**Comment by zheins** [comment]
@jjgao I renamed the tcga studies.

**Comment by jjgao** [comment]
@zheins @pieterlukasse let's merge it and do another pr for cptac data.

@zheins could you also put license for tcga if not in place yet?

@pieterlukasse any other comments before we merge it?

**Comment by pieterlukasse** [comment]
hi @zheins I checked one of the studies together with @pulyakhina and we found that for the study we checked there were some problems:
- missing html validation report
- missing meta_study.txt file

See https://github.com/zheins/datahub/blob/79b5303b210ba44ecc2f8befd8367c2df41c6fae/public/acbc_mskcc_2015.tar.gz 

Is this problem perhaps found in all files?

**Comment by zheins** [comment]
@pieterlukasse - You're right. Our internal pipelines generate meta_study.txt and I didn't run the validator on all the studies. @jjgao how should we go about handling this? I can make another hack in our pipeline to get those meta files, but I know many of these studies will fail validation.

@jjgao I added the license file to all studies.

**Comment by pulyakhina** [comment]
@pieterlukasse @zheins I've run the validation script (from the master branch) on each study from the pull request:
```
./validate.py -s /path/to/study -n
```

In total, 20 studies out of 146 could be validated. 126 contained errors. I'm listing the errors here (I grouped identical errors, so the list you see is the list of 59 types of errors that were generated). The number next to the word "ERROR" indicates how many times this error was seen (e.g., error "no valid study file detected" was seen 100 times).

```
   1 ERROR: data_mutations_extended.txt: lines [111, 112, 115, ]: column 25: Value in column 'Validation_Status' is invalid; value encountered
   1 ERROR: data_mutations_extended.txt: lines [3, 8, 9, ]: column 50: Value in column 'n_ref_count' is invalid; value encountered
   1 ERROR: data_mutations_extended.txt: lines [3, 8, 9, ]: column 51: Value in column 'n_alt_count' is invalid; value encountered
   1 ERROR: data_mutations_extended.txt: lines [39182, 39183, 39184, ]: column 16: Sample ID not defined in clinical file; value encountered
   1 ERROR: meta_CNA.txt: Missing field 'profile_description' in meta file
   1 ERROR: meta_CNA_RAE.txt: Missing field 'data_filename' in meta file
   1 ERROR: meta_CNA_consensus.txt: Missing field 'data_filename' in meta file
   1 ERROR: meta_RNA_Seq_expression_capture.txt: Missing field 'data_filename' in meta file
   1 ERROR: meta_RNA_Seq_expression_median.txt: Invalid stable id for genetic_alteration_type 'MRNA_EXPRESSION', data_type 'Z-SCORE'; expected one of [mrna_U133_Zscores, rna_seq_mrna_median_Zscores, mrna_median_Zscores, rna_seq_v2_mrna_median_Zscores, mirna_median_Zscores, mrna_merged_median_Zscores, mrna_zbynorm, rna_seq_mrna_capture_Zscores]; value encountered
   1 ERROR: meta_RNA_Seq_mRNA_median_Zscores.txt: Invalid stable id for genetic_alteration_type 'MRNA_EXPRESSION', data_type 'Z-SCORE'; expected one of [mrna_U133_Zscores, rna_seq_mrna_median_Zscores, mrna_median_Zscores, rna_seq_v2_mrna_median_Zscores, mirna_median_Zscores, mrna_merged_median_Zscores, mrna_zbynorm, rna_seq_mrna_capture_Zscores]; value encountered
   1 ERROR: meta_expression.txt: Missing field 'profile_description' in meta file
   1 ERROR: meta_expression_median.txt: Invalid stable id for genetic_alteration_type 'MRNA_EXPRESSION', data_type 'Z-SCORE'; expected one of [mrna_U133_Zscores, rna_seq_mrna_median_Zscores, mrna_median_Zscores, rna_seq_v2_mrna_median_Zscores, mirna_median_Zscores, mrna_merged_median_Zscores, mrna_zbynorm, rna_seq_mrna_capture_Zscores]; value encountered
   1 ERROR: meta_expression_miRNA.txt: Invalid stable id for genetic_alteration_type 'MRNA_EXPRESSION', data_type 'CONTINUOUS'; expected one of [mrna_U133, rna_seq_mrna, rna_seq_v2_mrna, mirna, mrna, rna_seq_mrna_capture]; value encountered
   1 ERROR: meta_fusion.txt: Missing field 'data_filename' in meta file
   1 ERROR: meta_fusions.txt: Missing field 'profile_description' in meta file
   1 ERROR: meta_fusions.txt: Missing field 'profile_name' in meta file
   1 ERROR: meta_linear_CNA.txt: Invalid stable id for genetic_alteration_type 'COPY_NUMBER_ALTERATION', data_type 'CONTINUOUS'; expected one of [linear_CNA]; value encountered
   1 ERROR: meta_mRNA_median_Zscores.txt: Invalid stable id for genetic_alteration_type 'MRNA_EXPRESSION', data_type 'Z-SCORE'; expected one of [mrna_U133_Zscores, rna_seq_mrna_median_Zscores, mrna_median_Zscores, rna_seq_v2_mrna_median_Zscores, mirna_median_Zscores, mrna_merged_median_Zscores, mrna_zbynorm, rna_seq_mrna_capture_Zscores]; value encountered
   1 ERROR: meta_mRNA_outliers.txt: Missing field 'data_filename' in meta file
   1 ERROR: meta_mRNA_outliers.txt: Missing field 'show_profile_in_analysis_tab' in meta file
   1 ERROR: meta_mRNA_unified.txt: Missing field 'data_filename' in meta file
   1 ERROR: meta_mRNA_unified_Zscores.txt: Missing field 'data_filename' in meta file
   1 ERROR: meta_mRNA_unified_Zscores.txt: Missing field 'show_profile_in_analysis_tab' in meta file
   1 ERROR: meta_methylation_hm27.txt: Invalid stable id for genetic_alteration_type 'METHYLATION', data_type 'CONTINUOUS'; expected one of [methylation_hm27, methylation_hm450]; value encountered
   1 ERROR: meta_miRNA_median_Zscores.txt: Invalid stable id for genetic_alteration_type 'MRNA_EXPRESSION', data_type 'Z-SCORE'; expected one of [mrna_U133_Zscores, rna_seq_mrna_median_Zscores, mrna_median_Zscores, rna_seq_v2_mrna_median_Zscores, mirna_median_Zscores, mrna_merged_median_Zscores, mrna_zbynorm, rna_seq_mrna_capture_Zscores]; value encountered
   2 ERROR: meta_CNA.txt: Missing field 'profile_name' in meta file
   2 ERROR: meta_RNA_Seq_expression_median.txt: Missing field 'data_filename' in meta file
   2 ERROR: meta_expression.txt: Missing field 'data_filename' in meta file
   2 ERROR: meta_expression_Zscores.txt: Missing field 'data_filename' in meta file
   2 ERROR: meta_mutations_extended.txt: Missing field 'profile_description' in meta file
   2 ERROR: meta_mutations_extended.txt: Missing field 'profile_name' in meta file
   3 ERROR: data_expression.txt: line 2: columns [3, 4, 5, ]: Value is neither a real number nor NA; value encountered
   3 ERROR: meta_mRNA_median_Zscores.txt: Missing field 'show_profile_in_analysis_tab' in meta file
   4 ERROR: meta_CNA.txt: Invalid stable id for genetic_alteration_type 'COPY_NUMBER_ALTERATION', data_type 'DISCRETE'; expected one of [cna, cna_rae, cna_consensus, gistic]; value encountered
   4 ERROR: meta_RNA_Seq_mRNA_median_Zscores.txt: Missing field 'data_filename' in meta file
   4 ERROR: meta_mutations_extended.txt: Invalid stable id for genetic_alteration_type 'MUTATION_EXTENDED', data_type 'MAF'; expected one of [mutations]; value encountered
   5 ERROR: meta_expression_merged_median_Zscores.txt: Missing field 'data_filename' in meta file
   5 ERROR: meta_expression_miRNA.txt: Missing field 'data_filename' in meta file
   5 ERROR: meta_fusions.txt: Invalid stable id for genetic_alteration_type 'FUSION', data_type 'FUSION'; expected one of [fusion]; value encountered
   5 ERROR: meta_miRNA_median_Zscores.txt: Missing field 'data_filename' in meta file
   6 ERROR: meta_expression_merged_median_Zscores.txt: Missing field 'show_profile_in_analysis_tab' in meta file
   8 ERROR: meta_methylation_hm450.txt: Missing field 'data_filename' in meta file
  10 ERROR: data_expression_median.txt: line 2: columns [3, 4, 5, ]: Value is neither a real number nor NA; value encountered
  10 ERROR: meta_methylation_hm27.txt: Missing field 'data_filename' in meta file
  11 ERROR: meta_CNA.txt: Missing field 'show_profile_in_analysis_tab' in meta file
  11 ERROR: meta_RNA_Seq_v2_expression_median.txt: Missing field 'data_filename' in meta file
  11 ERROR: meta_RNA_Seq_v2_mRNA_median_Zscores.txt: Missing field 'data_filename' in meta file
  12 ERROR: meta_mRNA_median_Zscores.txt: Missing field 'data_filename' in meta file
  14 ERROR: -: No sample attribute file detected
  14 ERROR: meta_expression_median.txt: Missing field 'data_filename' in meta file
  16 ERROR: meta_fusions.txt: Missing field 'data_filename' in meta file
  16 ERROR: meta_linear_CNA.txt: Missing field 'data_filename' in meta file
  32 ERROR: Could not determine the file type. Please check your meta files for correct configuration.; value encountered
  36 ERROR: meta_CNA.txt: Missing field 'data_filename' in meta file
  53 ERROR: Could not determine the file type. Did not find expected meta file fields. Please check your meta files for correct configuration.
  57 ERROR: meta_mutations_extended.txt: Missing field 'show_profile_in_analysis_tab' in meta file
 100 ERROR: -: Cancer type needs to be defined for a study. Verify that you have a study file and have defined the cancer type correctly.
 100 ERROR: -: No valid study file detected
 107 ERROR: meta_mutations_extended.txt: Missing field 'data_filename' in meta file
```
There are 59 types of errors in total. As I said, only 20 studies do path the validation...

**Comment by zheins** [comment]
@pulyakhina thanks for checking that out! It's pretty much what I expected - most of these studies were curated before we had data validation and when we were less strict on data checks. Fixing all these issues is not a trivial task. @jjgao what do you think? All of these studies do import into the portal (I imported them a few weeks back to the public site).

**Comment by zheins** [comment]
@pieterlukasse @jjgao 
I added the meta files and added `data_filename` to all meta fields that were missing it. @pulyakhina We decided that we would merge this PR as is for now and work out a plan to address the remaining issues that the validator finds.

**Comment by pieterlukasse** [comment]
thanks @zheins, we will validate this set again.

**Comment by jjgao** [comment]
Thanks, @zheins!

I am going to merge this PR now since we have a few requests to download the data.

**Comment by pulyakhina** [comment]
@zheins @pieterlukasse here is a table where all studies from the pull request are listed, as well as their validation status ("Yes" means the study runs through the validateData.py without errors; "Intermediate" means there are errors which can be easily fixed, e.g., an empty line or an extra comment line; "No" means there are errors and they cannot be fixed automatically, e.g., missing data files). I'll keep updating it as I go through the studies.
https://docs.google.com/spreadsheets/d/1jboHbvMeQPHX-IUlibjAvZAgoFHy1KWu36ioYE4bohY/edit#gid=57298400

(@zheins I don't think you can see it automatically, perhaps you could tell me your email address and I could share the table with you?)

**Comment by pieterlukasse** [comment]
@pulyakhina this table applies to #11 as well right?

**Comment by pulyakhina** [comment]
@pieterlukasse I haven't updated it for the most recent version yet... (so it applies to the earlier version)

**Pull request merged**
