### PR TITLE
provisional studies cleanup

### PR DESCRIPTION
**Pull request by yichaoS**
Clean up of all provisional studies from @ritikakundra from @dionnezaal spreadsheet

-- Maf renaming (data_mutations_uniprot -> data_mutations_extended) and removed readMe
-- case list (https://github.com/cBioPortal/datahub/issues/123)
-- removed duplicate expression files and empty lines (@sandertan @dionnezaal)
-- added missing ov_tcga (@dionnezaal)
-- fixed meso maf (https://github.com/cBioPortal/datahub/issues/57)
-- renaming of segment files (https://github.com/cBioPortal/datahub/pull/152 comments from @sandertan)
-- Redid validation reports
-- Reannotate w/ updated annotator (mskcc and uniform isoforms included)

### CODE REVIEW

**Comment by ritikakundra** [comment]
@pieterlukasse Does all_cases_with_mutation_data category still imply all sequenced samples regardless of the number of mutations?

**Comment by pieterlukasse** [comment]
@ritikakundra yes, `all_cases_with_mutation_data` just seems to be a bad name...but as far as I could see in the code it does stand for  all sequenced samples regardless of the number of mutations.

**Comment by dionnezaal** [comment]
The following studies contain both the old seg files (`*_tcga__data_cna_hg19.seg` and `*_tcga__data_cna_hg19.seg.txt`) and the new seg files (`data_cna_hg19.seg` and `meta_cna_hg19.seg`). Old seg files should be removed otherwise, the importer fails:
`chol_tcga, laml_tcga, lgg_tcga, lihc_tcga, lusc_tcga, meso_tcga, paad_tcga, pcpg_tcga, prad_tcga, sarc_tcga, skcm_tcga, stad_tcga, tgct_tcga, thca_tcga, thym_tcga, ucec_tcga, ucs_tcga, uvm_tcga`

**Comment by dionnezaal** [comment]
18 studies still contain data_mutations_uniprot.txt and the README file: `chol_tcga, lihc_tcga, paad_tcga, sarc_tcga, tgct_tcga, ucec_tcga, laml_tcga, lusc_tcga, pcpg_tcga, skcm_tcga, thca_tcga, ucs_tcga, lgg_tcga, meso_tcga, prad_tcga, stad_tcga, thym_tcga, uvm_tcga`

**Comment by pieterlukasse** [comment]
nice, I saw it at https://circleci.com/gh/cBioPortal/datahub/11, thanks

**Comment by angelicaochoa** [comment]
@pieterlukasse I added re-annotations for 14 of the TCGA provisional studies so far:

```
`datahub/cleanup`

dlbc_tcga
ov_tcga
brca_tcga
acc_tcga
chol_tcga
coadread_tcga
meso_tcga
pcpg_tcga
thym_tcga
uvm_tcga
gbm_tcga
hnsc_tcga
kirc_tcga
lihc_tcga
```

**Comment by dionnezaal** [comment]
Currently working together with @yichaoS @ritikakundra to resolve last warnings and errors in TCGA provisional studies: #173

**Comment by pieterlukasse** [comment]
Checked and approved :+1:

**Pull request merged**
