### PR TITLE
December Public Release Studies

### PR DESCRIPTION
**Pull request by Rima-Waleed**
Study_ID | Testing Instance Link | Sample Count
-- | -- | --
hcc_msk_2024 | https://private.cbioportal.mskcc.org/study/summary?id=hcc_msk_2024 | 1,370 Samples
brca_dfci_2020 | https://private.cbioportal.mskcc.org/study/summary?id=brca_dfci_2020 | 59 Samples
pancreas_msk_2024 | https://private.cbioportal.mskcc.org/study/summary?id=pancreas_msk_2024 | 395 Samples
panet_msk_2018 | https://private.cbioportal.mskcc.org/study/summary?id=panet_msk_2018 | 96 Samples
msk_ctdna_vte_2024 | https://www.cbioportal.org/study/summary?id=msk_ctdna_vte_2024 | 5,567 Samples
prostate_msk_2024 | https://private.cbioportal.mskcc.org/study/summary?id=prostate_msk_2024 | 2,260 Samples
asclc_msk_2024 | https://private.cbioportal.mskcc.org/study/summary?id=asclc_msk_2024 | 31 Samples
pcnsl_msk_2024 | https://private.cbioportal.mskcc.org/study/summary?id=pcnsl_msk_2024 | 86 Samples
msk_chord_2024 | https://www.cbioportal.org/study/summary?id=msk_chord_2024 | 25,040 Samples
| | Total | 34,904

Notes: 

- **brca_dfci_2020**: CNA, enrichment data, drug IC50 data pending from author _(author is working on producing a cBioPortal-compatible version of the entire DFCI MBC cohort)_
- **prad_wch_2024**: RNA-seq, CNV, mutational signature, & methylation data pending from author (followed-up: no response yet)
- **prostate_smc_2023**: RNA-seq, z scores, protein quantification data, age time point pending from author
- **pcnsl_msk_2024**: Author cannot share clinical details as the study is part of a clinical trial: IMPACT-IDs, PFS, panel, clinical data, age time point. Oncotree codes pending from author. Note: Cohort shows 44 patients, while paper indicated 46 patients were enrolled; paper indicates that "Two patients refused to continue trial treatment because of personal choice"
- **pancreas_msk_2024**: additional clinical data pending from author
- **prostate_msk_2024**: additional clinical data pending from author. Note: only 2,257 patients met the study inclusion criteria
- **csf_msk_2024**: held off for closer review. 
- **prad_wch_2023**: study removed for mutation artifacts.
- **prostate_msk_2017**: duplicate study (prad_mskcc_2017)
- **prostate_smc_2023**: study removed for gene discrepancy

### CODE REVIEW

**Comment by rmadupuri** [comment]
Thanks @Rima-Waleed! A few additional improvements we can consider.

**csf_msk_2024:**
- [ ] The Cancer type counts doesn't match paper (lung cancer (n = 188), breast cancer (n = 150) and gliomas (n = 148)) and 85 CSF samples had no evidence of CNS
- [ ]  Has matched normals. Missing somatic status
- [ ] Study missing gene panel matrix (IMPACT468 (n = 274) or IMPACT505 (n = 733))
- [ ]  Can we collect mutational signatures from the PI's?
- [ ] Is the MSK-ACCESS cfDNA data included in the paper?
- [ ] Can we update the OS description to include the date of first CSF collection? (For patients with multiple CSF samples, the first CSF sample was selected for analysis)
- [ ] Can we collect patient age at dx if possible? Cohort includes pediatric patients. (Supp Table 1 includes summary of Age and Sex)
- [ ] What does `ctDNA status` in portal refer to? Per paper, 489 samples has at least one somatic genetic alteration. These samples were categorized as ctDNA positive. Portal counts are different.
- [ ] paper indicates 3944 somatic non-synonymous mutations were detected across the 489 samples. The data_mutations.txt file has 3944 mutations across 471 samples. Doesnt match the paper stats.  
- [ ] Can we check the ROS1::CD74 and other fusions from Fig 1c? portal shows fewer events. 

**msk_chord_2024:**
- [ ] Is ARCHER_Panel attribute required?
- [ ] Timeline events are a mix of caps and small cases. Should be normalized. See Timeline events Table. 

**prostate_msk_2017:**
- [ ] Remove `Impact Panel Version` attribute. There's already `Gene Panel` attr
- [ ] Missing Somatic Status attr
- [ ] Can we double check the BRCA2 %. Should be 7%.

**prad_wch_2024:**
- [ ] Missing Oncotree Code, CT, CTD. Add them as Prostrate Cancer? 
- [ ] Missing somatic status
- [ ] Clinical attributes with no data (0% Freq) can be removed.
- [ ] Does `-` in Tissue Types for Methylation, RNA-Seq mean `Not Profiled`? Can it be replaced?
- [ ] Is the RNA, and DNA-methylation sequencing data available?
- [ ] Oncoplot [Fig 1B](https://aacrjournals.org/view-large/figure/15466291/154fig1.jpeg) also shows CNV's and mutational Signatures. Can we request the authors? 

**pcnsl_msk_2024:**
- [ ] Replace `Primary` with `Recurrent` in the study name.
- [ ] Update panel in study description to `MSK-HemePACT`. Also study is missing the gene panel matrix info. 
- [ ] Update in the study description `A Phase II study assessing long-term response to ibrutinib monotherapy in recurrent or refractory CNS lymphoma.` Note the casing.
- [ ] 29 samples missing CT, CTD. 
- [ ] PFS endpoint was analyzed in paper. Can we request the data?
- [ ] Patient IDs are referred to as sequential numbers (`#1`,`#2`, etc.) in the paper (see Supp Table 3). Can we add the patient display names to match this numbering?

**Comment by ritikakundra** [comment]
https://private.cbioportal.mskcc.org/study/summary?id=hcc_msk_2024

- [ ] do we know the start and stop dates for OS data?
- [ ] Can we change the descriptions not to include MSK-related data like MPath etc?

https://private.cbioportal.mskcc.org/study/summary?id=brca_dfci_2020

- [ ] The timeline data for tx is not a duration? Its just a single event?
- [ ] Text in the paper says, "WES was successfully performed on 59 biopsies from 58 patients". Can we confirm that its 58 patients or 59? - Confirmed that there are 58 patients with 59 tumors. 408 has 2 samples: I still see 59/59
- [ ] Where was the seg data collected from? Which supp file?

csf_msk_2024:

- [ ] Why do we need to request for the panel file or other clinical data? These look like impact cases so can't we get them ourselves?
- [ ] is the MSK-ACCESS cfDNA data included in the paper?: Q not answered
- [ ] Question asked on slack

msk_chord_2024:

- [ ] Sex, ethnicity values are all upper case
- [ ]

**Comment by schultzn** [comment]
Thank you for working on this.  Here are my comments. 

https://private.cbioportal.mskcc.org/study/summary?id=brca_dfci_2020

- segmented copy-number data looks wrong... everything is deleted, resulting in 100% FGA

https://private.cbioportal.mskcc.org/study/summary?id=prostate_smc_2023

- vital status does not seem to be useful.. they are all living, but no time until last follow up is given
- queries don't seem to work in this study, I can only access study and patient view
- variant allele counts and frequencies are missing .. not available, I assume?
- have not all samples been sequenced for mutations?

https://private.cbioportal.mskcc.org/study/summary?id=asclc_msk_2024

- structural variant frequencies appear to be very high


https://private.cbioportal.mskcc.org/study/summary?id=pcnsl_msk_2024

- CDKN2A missing from gene copy-number alterations gene table
- mutations only available for 69.8% of samples? do the other 30% of samples simply have no mutations?
- gene panel information is missing (study description says targeted though)

https://private.cbioportal.mskcc.org/study/summary?id=prad_wch_2024

- variant allele counts and frequencies are missing .. not available, I assume?
- germline mutations do not seem to be properly filtered out, see MUC6 and FLG as examples


https://private.cbioportal.mskcc.org/study/summary?id=prostate_msk_2017

- why is this a new study? It was published in 2017 and included a link to the cBioPortal study in the paper
- ERG fusions appear to be missing from structural variants

https://www.cbioportal.org/study/clinicalData?id=msk_chord_2024

- LAB TESTs not showing up as line charts in patient view

**Comment by ritikakundra** [comment]
https://cbioportal.mskcc.org/study/summary?id=brca_dfci_2020:
1. I see Tx data is still there. Were we not removing it? And also I don't see them on the timeline

https://private.cbioportal.mskcc.org/study/summary?id=prostate_smc_2023
1. Did we re-produce the genomics figure against the paper? I am trying to reproduce fig1e but not able to.
2. The description says WXS of 35 but its 22 that were. I think that can be misleading. Can we modify that?

**Review by rmadupuri — APPROVED** [review]

**Pull request merged**
