### PR TITLE
added RNA-Seq expr files for prad_su2c_2015

### PR DESCRIPTION
**Pull request by yichaoS**

### CODE REVIEW

**Comment by yichaoS** [comment]
@sandertan Could you help fix the gene table the validator use. So "5S_RRNA" wouldn't be identified as a invalid gene symbol here?

**Comment by yichaoS** [comment]
@sandertan @jjgao I saw we have the discussion here a while ago but discontinued: https://github.com/cBioPortal/datahub/issues/315

**Comment by yichaoS** [comment]
@jjgao Is there a list of studies with files that needs to be renamed?

**Comment by jjgao** [comment]
@yichaoS let's get this merged and pushed to production soon.

**Comment by yichaoS** [comment]
@jjgao just merged this. We do need some further cleanup for the separated exp files. Will do that in another PR then.

**Comment by jjgao** [comment]
@yichaoS are you going to push this to public portal soon?

**Comment by yichaoS** [comment]
@jjgao Sure. I'll schedule for today and it will be in tomorrow. The data is downloadable already tho, it's in MSK storage.

**Pull request merged**
