### PR TITLE
Update seed database to 2.7.3 and include new genes, aliases and cancer types

### PR DESCRIPTION
**Pull request by sandertan**
This can be merged when ~1.19.0~ 2.0.0 is released on GitHub. The README links to the `cgds.sql` of this release: https://raw.githubusercontent.com/cBioPortal/cbioportal/v2.0.0/db-scripts/src/main/resources/cgds.sql

# What?
cBioPortal 2.0.0 uses database schema 2.7.3. This PR updates the seed database to 2.7.3 and includes updated tables for genes, aliases and cancer types.

Output from tests on CircleCi:
```
Genes in seed database: 61170

Gene aliases in seed database: 68083

Cancer types in seed database: 852

Gene symbols in HUGO_GENE_SYMBOL column in gene table are unique

0 studies found in seed database

The "info" table is correctly filled.

GENESET_VERSION in info table: msigdb_6.1

These tests ran with cgds.sql from cBioPortal master branch, schema: 2.7.3
```

Previous seed database (2.7.2): https://github.com/cBioPortal/datahub/pull/448 CircleCI output:

```
Genes in seed database: 60070

Gene aliases in seed database: 66840

Cancer types in seed database: 839

Gene symbols in HUGO_GENE_SYMBOL column in gene table are unique

0 studies found in seed database

The "info" table is correctly filled.

DB_SCHEMA_VERSION: 2.7.2

GENESET_VERSION: msigdb_6.1
```

### CODE REVIEW

**Comment by n1zea144** [comment]
@sandertan @yichaoS I notice there are 852 cancer types in seed database, but 853 records in the production cgds_public type_of_cancer table.  Do you know which one is missing?  I suppose its not required in the studies in datahub?

**Comment by sandertan** [comment]
@n1zea144 The missing cancer type is not required in any of the current Datahub studies, else the weekly check would have failed. I don't know which one is missing. I can check which one, but I'm not sure it's worth the effort. It's probably the latest one added. I updated the cancer types last month.

If any new or updated studies fail because of missing cancer-types, I'll update the cancer-types table ASAP.

**Comment by Sjoerd-van-Hagen** [comment]
@sandertan @n1zea144 so this one can get merged now that 2.0.0 is released?

**Comment by sandertan** [comment]
Rebased on master.

**Comment by Sjoerd-van-Hagen** [comment]
@sandertan ready to be merged?

**Comment by sandertan** [comment]
@n1zea144 Rebased it on master. Are you ok with merging this?

**Comment by Sjoerd-van-Hagen** [comment]
Thanks @n1zea144 @inodb

**Pull request merged**
