### PR TITLE
Feb News release Studies

### PR DESCRIPTION
**Pull request by sbabyanusha**
Cancer studies updated in this pull request:

1. Appendiceal_msk_2022 - https://cbioportal.org/study/summary?id=appendiceal_msk_2022
2. gist_msk_2022 - https://cbioportal.org/study/summary?id=gist_msk_2022
3. coadread_mskresistance_2022 - https://cbioportal.org/study/summary?id=coadread_mskresistance_2022
4. paired_bladder_2022 - https://cbioportal.org/study/summary?id=paired_bladder_2022
5. nst_nfosi_ntap - https://cbioportal.org/study/summary?id=nst_nfosi_ntap

# checks
For all pull requests:
- [x] Passes validation

For a new study (in addition to above):
- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [ ] is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [x] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [x] clinical sample and patient data with meta files
- [x] mutations data with meta files
- [x] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [x] CNA data with meta files
- [x] CNA segment data with meta files
- [x] Expression data including z-scores with meta files
- [x] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

### CODE REVIEW

**Comment by jjgao** [comment]
paired_bladder_2022:
- study name is different from convetion
- do we need clinical fields: `12-245 part A consented`, `12-245 part C consented`, and `collaboration identifier` (only 1% samples have it)

nst_nfosi_ntap:
- the study name is different from convention

coadread_mskresistance_2022:
- do we need clinical fields: `12-245 part A consented`, `12-245 part C consented`, and `collaboration identifier`
- It's a little confusing that "cellline" is in sample type but not "pdx". They are coded in sample class. I think adding both cellline and pdx to sample_type would make it less confusing but not sure if that's the convention.
image
image

gist_msk_2022
- should we release `patient current age` or `age at diagnosis/sequencing`?

**Comment by schultzn** [comment]
**Appendiceal Cancer (MSK,J Clin Oncol 2022)**
Add space after "MSK,"" in title to --> "Appendiceal Cancer (MSK, J Clin Oncol 2022)""

**Gastrointestinal Stromal Tumor (MSK, 2022)**
Inconsistent naming. Do we include the journal name in the study name?

**Colorectal Cancer (MSK, Cancer Discovery 2022)**
study ID is coadread_mskresistance_2022 - does not follow our naming conventions
C-FFDWJM has many mutations with low variant allele frequencies... possible artifacts!

**Bladder Cancer (MSK, Cell Reports 2022)**
Study ID does not match our naming convention

**Nerve Sheath Tumors (Johns Hopkins, Sci Data 2020)**
Patient ID for 2-031_Cell_Line needs to be corrected to JH-2-031

**Comment by sbabyanusha** [comment]
Thanks for the review @schultzn @jjgao 
- The study IDs which do not follow cbioportal naming convention are requested by the PI's as they have already created public links for their manuscripts.
- Colorectal Cancer (MSK, Cancer Discovery 2022) - C-FFDWJM has many mutations with low variant allele frequencies... possible artifacts!-- It is a resistance specimen after targeted therapy.

**Comment by rmadupuri** [comment]
Thanks @jjgao @schultzn, for `nst_nfosi_ntap` we have dropped the year from the study ID in https://github.com/cBioPortal/datahub/pull/1762 as this is an ongoing study. The samples are from a Biobank https://www.synapse.org/#!Synapse:syn4939902/wiki/235907 and the authors submitted a pilot batch to us and are currently preparing to release another batch of samples and data which are not in the scope of the linked publication.

**Pull request merged**
