### PR TITLE
Add symlinks for path reports

### PR DESCRIPTION
**Pull request by inodb**
For each path report create a symlink with the PATIENT_ID.number (some patients
have multiple reports). This way we can request the pathology report for a
certain patient through a simple URL, instead of having to store a mapping of
patient to report somewhere in cBioPortal.

See make_symlinks.sh for the script to make the symlinks

### CODE REVIEW

**Comment by pieterlukasse** [comment]
hi @inodb, I can't review the script, see screenshot:
image  , but I learned about a new limit of github, thanks! :smile: 

Who will run the script and when will this happen? I.e. how to make sure this list of symlinks is kept up to date?

**Comment by jjgao** [comment]
Should we just move all path reports to our http server?

**Comment by pieterlukasse** [comment]
@jjgao sounds good to me, unless we have a specific versioning use case for which we would like to keep hosting it here...

**Comment by jjgao** [comment]
Created an issue: https://github.com/cBioPortal/datahub/pull/132

I think it's still a good idea to merge this pull request and we can use this symlink trick on our http server as well.

**Comment by inodb** [comment]
@jjgao we actually already have this running in production: https://github.com/cBioPortal/cbioportal-frontend/blob/53b1df564f2526c0d6d0734f4bc95728f0610a54/src/pages/patientView/clinicalInformation/PatientViewPageStore.ts#L226-L255. The url is pointing to my fork (protected the branch to not accidentally remove the commit). I thought we wanted to add path reports as files that can be attached to a patient. Then have them show up in a new files tab.

**Comment by jjgao** [comment]
@inodb thanks. I was thinking of adding links of files in our database but not the real pdf files.

**Comment by inodb** [comment]
I guess we can close this since we decided to move the path reports to our http server

**Pull request closed without merging**
