### PR TITLE
Added Microbiome data to Pancan studies

### LINKED ISSUE #1095: Microbiome data for TCGA
It would be very interesting if we can integrate the microbiome from [this study](https://www.nature.com/articles/s41586-020-2095-1).

We can use generic assay to host the data.

We may need to contact the authors to get he matrix of sample vs species.

### PR DESCRIPTION
**Pull request by rmadupuri**
# What?
Fix #1095 #241 

Cancer studies updated in this pull request:
- All pancan studies except LAML (No data available)

Testing instances: 
1. http://triage.cbioportal.mskcc.org/study/summary?id=coadread_tcga_pan_can_atlas_2018
2. http://triage.cbioportal.mskcc.org/study/summary?id=brca_tcga_pan_can_atlas_2018

### CODE REVIEW

**Comment by rmadupuri** [comment]
Hi @jjgao @dippindots @ritikakundra, I have tested the microbiome import (See the testing links above). Works fine when I select a subset of entities.

Screen Shot 2020-06-18 at 1 08 15 PM

But when I select all entities (~1400) its was rendering for a while and becomes unresponsive (not sure if its my internet).

**Comment by dippindots** [comment]
Thanks @rmadupuri for making those data available! I think adding all tracks may problematic since the action that adding a thousand tracks on oncoprint may causing some problems. It's really require lots of resources to render those tracks. The fetching speed of generic assay data itself should be fine. An [improvement of the generic assay meta endpoint](https://github.com/cBioPortal/cbioportal/issues/7448) is also merged.

**Comment by adamabeshouse** [comment]
@dippindots yeah, 1000 tracks is going to be really hard on the oncoprint. i dont think it can handle it.

**Comment by jjgao** [comment]
We should probably put a limit, just like we put a limit to the size of genes times samples.

**Comment by dippindots** [comment]
@jjgao I created an issue at here: https://github.com/cBioPortal/cbioportal/issues/7650. Do you think `50` is a  reasonable number?

**Comment by jjgao** [comment]
@rmadupuri we can merge this once https://github.com/cBioPortal/cbioportal/issues/7656 is done.

**Comment by dippindots** [comment]
@rmadupuri @jjgao https://github.com/cBioPortal/cbioportal/issues/7656 is finished and merged.

**Comment by rmadupuri** [comment]
Thank you @dippindots.  @jjgao can we merge this PR?

**Comment by jjgao** [comment]
@rmadupuri yes, please feel free to merge.

**Comment by jjgao** [comment]
@rmadupuri @ritikakundra Great job getting this merged! Please write a news item when they are released to the public portal.

**Pull request merged**
