### PR TITLE
coad_caseccc_2015: Added new public study

### LINKED ISSUE #336: Guda et al., Novel recurrently mutated genes in African American colon cancers, PNAS 2015
Please keep this checklist for curation of a new study.

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [x] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [x] Document the curation process, e.g. how and by whom the data was transformed
- [x] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [x] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

### PR DESCRIPTION
**Pull request by rmadupuri**
Fix #336 

Testing Instance: https://triage.cbioportal.mskcc.org/study/summary?id=coad_caseccc_2015

### CODE REVIEW

**Comment by yichaoS** [comment]
Comments from QC:
- [ ] typo in meta mutation: 'whole-emote sequencing'
- [ ] change 'HAS_MATCHED_NORMAL' in clinical file into 'somatic_status'
- [ ] 'cancer type' & 'cancer type details' graph were not generated on study view for some reason
- [ ] didn't find the musig data
- [ ] query result for mutation view is different from the paper: 
Portal result: https://bit.ly/2x3tfcg
Paper Figure: https://www.pnas.org/content/pnas/112/4/1149/F1.large.jpg
*Some mutation in discovery cohort AA doesn't seem to show up, maybe they are in the targeted sequencing they did (Table S5&S6, Agilent SureSelectXT bait library, 78 gene panel)
 - [ ] how about table S15 for the cosmic muts they collected in EPHA6 and FLCN? maybe need to ask @jjgao to see if we want to include it.

**Comment by rmadupuri** [comment]
Thanks @yichaoS. Also, should we include the validation cohort? This paper has the clinical and genomic data for validation cohort as well. (@ritikakundra ?)

**Comment by rmadupuri** [comment]
Thanks for the review @yichaoS. Updated the study based on comments. 

For point3, I think cancer_type and cancer_type_detailed are shown by default only if multiple cancer types exist. In this case, since its only COAD its not shown by default.

For point5, the mutations for EPHA6 & FLCN: https://triage.cbioportal.mskcc.org/results/mutations?Action=Submit&cancer_study_list=coad_caseccc_2015&case_set_id=coad_caseccc_2015_all&gene_list=EPHA6%0AFLCN&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coad_caseccc_2015_mutations&tab_index=tab_visualize

For point6, I don't think we should include the cosmic muts for EPHA6 & FLCN since they are for samples not studied in this cohort (TCGA and other external samples) Table S13

**Comment by rmadupuri** [comment]
@yichaoS @ritikakundra Added the mutsig data as well. `N` and `n`cols were not given. Derived those from `Mutation rate per Mb`(Table 1 in the paper). Can you confirm is that is right? Thanks!

**Comment by yichaoS** [comment]
@rmadupuri for mutsig data, I think those columns tho in the file, are not used in portal.

**Comment by ritikakundra** [comment]
@rmadupuri: here are my questions:

The sample size is actually 31, not 29. S1 says exome seq Yes to all 31 samples. Should we change that? Add the two samples back in with a sample note stating the reasoning

Add a note in the PR that curation was for Discovery cohort

You can add primary and met site based on tissue source?

Can we reduce the priority of matched normal ID and maybe add something more useful in like MSI-status etc?

**Comment by rmadupuri** [comment]
Thanks for the review @ritikakundra 

For point1: 2 samples from the discovery cohort were excluded from the analysis because one was hypermutated and sequencing of normal for second sample failed. The WES data of only 29 samples are given. I don't think we should include these two samples in the cohort because it then gives the sense that the 2 samples were sequenced and but have no mutations. What do you think?

Used Table1 from the paper for Mutsig

**Pull request merged**
