### PR TITLE
msk_spectrum_tme_2022: Add patient resource data and new mpif resource definitions

### PR DESCRIPTION
**Pull request by hweej**
Add minerva static links to the patient resource data.

# What?
Fix # .

Cancer studies updated in this pull request:
- msk_spectrum_tme_2022

# checks
For all pull requests:
- [ ] Passes validation

For a new study (in addition to above):
- [ ] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [ ] is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [ ] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [ ] clinical sample and patient data with meta files
- [ ] mutations data with meta files
- [ ] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [ ] Case-lists for all profiles.
- [ ] Manual checking (Niki or JJ): Triage or private Portal link here

### CODE REVIEW

**Comment by rmadupuri** [comment]
@hweej is this PR ready to be merged?

**Comment by hweej** [comment]
I think if we can get it loaded into private cbioportal that should be good enough for now. There are still some UI aspects we might want to get feedback on before we make it available on the public portal.

**Comment by rmadupuri** [comment]
Hi @hweej, is the PR still needed?

**Comment by hweej** [comment]
Hi @rmadupuri , This PR can be removed. It looks like the changes I put here already have made it into the master branch!
OK to remove.

**Pull request closed without merging**
