### PR TITLE
September 2024: Public Release Studies

### PR DESCRIPTION
**Pull request by Rima-Waleed**
Cancer studies updated in this pull request:

| Study_ID                       | Testing Instance Link         | Sample Count|
| -- | -- | -- |
|ptad_msk_2024         | https://private.cbioportal.mskcc.org/study/summary?id=ptad_msk_2024 | 104 Samples |
| plmeso_msk_2024        | https://private.cbioportal.mskcc.org/study/summary?id=plmeso_msk_2024 | 14 Samples |
| lms_msk_2024  | https://private.cbioportal.mskcc.org/study/summary?id=lms_msk_2024 | 472 Samples |
| pancan_mappyacts_2022       | https://www.cbioportal.org/study/summary?id=pancan_mappyacts_2022 | 788 Samples |
| cscc_ranson_2022      | https://private.cbioportal.mskcc.org/study/summary?id=cscc_ranson_2022 | 25 Samples |
|mbn_msk_2024 | https://private.cbioportal.mskcc.org/study/summary?id=mbn_msk_2024  | 396 Samples |
|ucec_msk_2024 | https://private.cbioportal.mskcc.org/study/summary?id=ucec_msk_2024  | 33 Samples |
| hcc_clca_2024 | https://private.cbioportal.mskcc.org/study/summary?id=hcc_clca_2024 | 494 Samples |
| brca_fuscc_2020 | https://private.cbioportal.mskcc.org/study/summary?id=brca_fuscc_2020 | 69 Samples |
| gist_msk_2023 | https://private.cbioportal.mskcc.org/study/summary?id=gist_msk_2023 | 469 Samples |
| mixed_msk_tcga_2021 | https://private.cbioportal.mskcc.org/study/summary?id=mixed_msk_tcga_2021 | 19 Samples |
| |  | 2,883 Samples |

### CODE REVIEW

**Comment by ritikakundra** [comment]
https://private.cbioportal.mskcc.org/study/summary?id=mixed_msk_tcga_2021:

- [ ] So this is germline study from MSK-IMPACT? The IDs are all different. Can we confirm these are not part of the main impact series?
- [ ] Do all the samples have a RAD51L mutation? The description says so.
- [ ] Need to confirm if the legalities are taken care of
- [ ] Confused about TCGA, were the TCGA samples sequenced on targeted panel?
- [ ] The paper is calling them with old TCGA IDs but we are not reporting the same way
Screenshot 2024-07-30 at 12 57 26 PM

**Comment by ritikakundra** [comment]
https://private.cbioportal.mskcc.org/study/summary?id=gist_msk_2023:

- [ ] Can we figure out the CDKN2A issue?
- [ ] Can institute source be normalized
- [ ] Race is also all upper case
- [ ] The paper talks about RFS curves, can we get that?
- [ ] There was a risk stratification done. Is that possible to curate?

**Comment by ritikakundra** [comment]
https://private.cbioportal.mskcc.org/study/summary?id=brca_fuscc_2020:

- [ ] The supp file has so much more clinical info. Why is that not part of the cohort?

**Comment by rmadupuri** [comment]
Thanks for working on this Rima! A couple of things we could improve:

https://private.cbioportal.mskcc.org/study/summary?id=ptad_msk_2024
- [ ] Update the Journal name to `Acta Neuropathologica`
- [ ] There are both TMB nonsynonymous and IMPACT TMB score attributes and the scores shouldnt vary much bt them, can we double check?
- [ ] Clinical: 
	- Attributes to Remove: Archer panel, Impact TMB Percentile (Across All Tumor Types), Impact TMB Percentile (Within Tumor Type), Impact TMB Score attributes, MSI comment
    - Attributes to Update: Sample coverage -> Sample Coverage
    - metastatic site has Epidural as value
    - Age attribute here refers to patients current age? Is this required?
- [ ] Timeline events: 
	- `Timeline Events Availability` table has some events capitalized and others in camel case. Can we normalize this? 
	- Can we check with authors if the timeline/treatment events are to be released. Dont see many discussed in the paper.
- [ ] From [Fig1](https://link.springer.com/article/10.1007/s00401-024-02736-8/figures/1) we can add the following clinical attributes
	- Cohort: Retrospective/Prospective
	- Subset: Treatment-refractory/Benign
	- PitNET shows 10 samples are metastatic, the Sample_Type attr on portal shows 11. Can we double check?
	- Lineage, Histologic features, Radiotherapy Status.
- [ ] The variant counts are a bit different in portal in comparison to fig1. There are a couple of variants missing for ex, missense mutation in TR-4 etc, can we double check?

https://private.cbioportal.mskcc.org/study/summary?id=plmeso_msk_2024
- [ ] Update `genomic near haploidization` to `genomic near-haploidization`. The paper defines it this way.
- [ ] Missing Somatic Status.
- [ ] Did the paper analyze 10 patients with GNH (from results section)? Portal shows 14. Cant verify as the full paper is not accessible.
- [ ] Paper mentions SETDB1 mutations are present in all GNH tumors. But only IMPACT505 has this gene. Guess we only show it profiled for the patients?

https://private.cbioportal.mskcc.org/study/summary?id=lms_msk_2024
- [ ] Paper mentions 195 soft tissue LMS & 238 uterine LMS were analyzed (total 433). portal shows 435 patients. 
- [ ] Remove MSI Comment, Varinat type?
- [ ] Does 1 in Necrosis mean `Yes`?
- [ ] Can we add `cm` to tumor size attr
- [ ] Progression Type, Metastatic Site has "
- [ ] Has Germline data. Is this supposed to be released?

**Comment by ritikakundra** [comment]
https://private.cbioportal.mskcc.org/study/summary?id=plmeso_msk_2024:

- [ ] There is survival data in the supp files
- [ ] Can we not get data for non-GNH cases?
- [ ] Supp files have more clinical data
- [ ] The SETDB1 issue that @rmadupuri brought up is still an issue I feel. The paper and portal are not in sync.

**Comment by ritikakundra** [comment]
cscc_ranson_2022:

- [ ] Can we normalize the genomic profiles tables? Sometimes it is the proper case and some are lower
- [ ] @rmadupuri @Rima-Waleed for the % off I think its cos the figure accounts for the synonymous mutations.
Screenshot 2024-08-30 at 4 35 44 PM

**Comment by ritikakundra** [comment]
https://www.cbioportal.org/study/summary?id=lms_msk_2024:

- [ ] The survival data needs more public friendly description. They are from IMPACT.
- [ ] All three need a general description with what is the anchor date and freeze date

**Comment by ritikakundra** [comment]
https://www.cbioportal.org/study/summary?id=pancan_mappyacts_2022:

- [ ] @sbabyanusha @Rima-Waleed I see the description and there are multiple attributes which define sample was RNA-Seq but genomic profiles does not include RNA-Seq data.
- [ ] There are two samples which are defined to be seq on a panel:https://www.cbioportal.org/patient?studyId=pancan_mappyacts_2022&caseId=Map178#navCaseIds=pancan_mappyacts_2022:Map178,pancan_mappyacts_2022:Map554; what is the gene panel for them?
- [ ] What does 'no' mean for Seq Platform?

**Comment by ritikakundra** [comment]
@Rima-Waleed for https://private.cbioportal.mskcc.org/study/summary?id=mixed_msk_tcga_2021:
You said *The samples are not DMP samples so they would not be part of the main cohort. But in the paper, under methods, it says:
Screenshot 2024-09-04 at 5 37 55 PM

**Comment by ritikakundra** [comment]
https://private.cbioportal.mskcc.org/study/summary?id=mbn_msk_2024:

- [ ] I still see "". Why are we still seeing them?

**Comment by ritikakundra** [comment]
https://private.cbioportal.mskcc.org/study/summary?id=ucec_msk_2024

- [ ] These are MSK-IMPACT cases so why is the ID different?

**Comment by ritikakundra** [comment]
https://private.cbioportal.mskcc.org/study/summary?id=hcc_clca_2024

- [ ] What is _60500 for AFP?
- [ ] What is _0.6 for CA19-9
- [ ] Can we confirm the PIVKA2 range?
- [ ]

**Comment by ritikakundra** [comment]
https://private.cbioportal.mskcc.org/study/summary?id=brca_fuscc_2020::

- [ ] Can we change the NGS ID to String and make it a 0 priority?

**Comment by jjgao** [comment]
- ptad_msk_2024: I noticed that CDSI data elements were included. Were they used in the publication? What's the general guideline/policy when to release CDSI data?

- lms_msk_2024: Is there any reason the germline mutations were not added into the mutations profile?<br/>
image

- lms_msk_2024: some patients have extremely long survival. Please double check. <br/>
image

- lms_msk_2024: was `institute source` used in the paper? 
image

- ucec_msk_2024: not sure how other studies are using this field, but maybe we could standardize this one? E.g. MSI_Status with High/Intermediate/Low values.
image

**Comment by schultzn** [comment]
Thanks @jjgao for the thorough review. I agree with all of your comments, and it would be good to make some of these checks standard for future studies, especially for MSK-IMPACT.

**Pull request closed without merging**
