### PR TITLE
Adding 33 Pan Can Studies

### PR DESCRIPTION
**Pull request by yichaoS**

### CODE REVIEW

**Comment by sandertan** [comment]
@yichaoS Fedde has fixed the issue with the crashing validateStudies, but we encountered a new issue with the ucec_tcga_pan_can_atlas_2018 study. Most likely, validation for this study requires more memory than our CircleCI VM has available. This should be solved if the study contains less warnings....

Could you remove the warnings that are given for every row? I've included the validation report that I've generated locally.

[ucec_tcga_pan_can_atlas_2018-validation.html.zip](https://github.com/cBioPortal/datahub/files/2206362/ucec_tcga_pan_can_atlas_2018-validation.html.zip)

**Comment by sandertan** [comment]
Also, I noticed the public portal does not show any mRNA samples on the Datasets page. Does this data originate from case lists? If so, could you check if the correct case lists are added?

screen shot 2018-07-24 at 13 28 22

**Comment by yichaoS** [comment]
@sandertan And for the meta study content update as well.

**Comment by jjgao** [comment]
@yichaoS maybe this is a good opportunity to fix the rna_seq names and the case lists? Some users are asking about that. Could you prioritize? @n1zea144

**Comment by yichaoS** [comment]
@jj I agree. We are undergoing fixing the RNA_seq file names and re-generate all the case lists.

**Comment by jjgao** [comment]
@yichaoS thank you!

**Comment by jjgao** [comment]
@yichaoS there was some discussion in #4586 related to the rna seq data. And I realized not only the file name but also the profile ID is not following our convention. Could you change `acc_tcga_pan_can_atlas_2018_mrna` to `acc_tcga_pan_can_atlas_2018_rna_seq_v2`?

image

http://www.cbioportal.org/api/studies/acc_tcga_pan_can_atlas_2018/molecular-profiles

**Comment by jjgao** [comment]
@yichaoS I think `xxx_tcga_pan_can_atlas_2018_mrna` might be a wrong/duplicated file. https://github.com/cBioPortal/datahub/issues/288. Could you check with @angelicaochoa ?

**Pull request merged**
