### PR TITLE
Cleanup non-provisional public studies

### PR DESCRIPTION
**Pull request by yichaoS**

### CODE REVIEW

**Comment by pieterlukasse** [comment]
Hi @yichaoS, I still see a lot of non TCGA provisional files being changed here. Is this also what you were intending to do? I thought this PR would only contain changes to tcga provisional studies.

**Comment by yichaoS** [comment]
@pieterlukasse Hi Pieter, you meant in PR 164 (https://github.com/cBioPortal/datahub/pull/164)? Those non-provisional studies should be the same as what currently in RC now. Seems like Circle CI tests all studies in a branch/PR, not just the changed ones.

**Comment by pieterlukasse** [comment]
@yichaoS no, I mean why are files like https://github.com/cBioPortal/datahub/blob/bb0ba5786d29abdab199d5d900469726b444444f/public/blca_dfarber_mskcc_2014/data_mutations_extended.txt and https://github.com/cBioPortal/datahub/blob/bb0ba5786d29abdab199d5d900469726b444444f/public/cellline_ccle_broad/data_cna_hg19.seg part of this PR? They are not part of the set of provisional TCGA studies.

**Comment by pieterlukasse** [comment]
hm...It looks like now all provisional studies are gone from this PR. @yichaoS : I think it should be the other way around.

**Pull request closed without merging**
